### ISSUE TITLE
cics.xml and .nodejsapp files tagged as ISO8859-1 when should be UTF-8 and are missing an XML declaration

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#101]
1. The .zosattributes file created as part of `generate bundle` does not have an entry for .xml or CICS bundle part files, so they are uploaded and tagged as ISO8859-1. I was expecting them to be tagged UTF-8. Could update .zosattributes to include:
   ```properties
   # Tag XML and CICS bundle part files as UTF-8
   *.xml UTF-8 UTF-8
   *.nodejsapp UTF-8 UTF-8
   *.transaction UTF-8 UTF-8
   *.file UTF-8 UTF-8
   *.jvmserver UTF-8 UTF-8
   *.library UTF-8 UTF-8
   *.pipeline UTF-8 UTF-8
   *.program UTF-8 UTF-8
   *.tcpipservice UTF-8 UTF-8
   *.urimap UTF-8 UTF-8
   *.webservice UTF-8 UTF-8
   *.osgibundle UTF-8 UTF-8
   *.warbundle UTF-8 UTF-8
   *.ebabundle UTF-8 UTF-8
   *.earbundle UTF-8 UTF-8
   *.policy UTF-8 UTF-8
   ```

2. The .xml and .nodejsapp bundle part files created as part of `generate bundle` results in .xml that does not have XML declaration information. I was expecting a declaration similar to that created by CICS Explorer:
   ```xml
   <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
   ```
   It appears that the declaration is optional in XML 1.0 (see https://stackoverflow.com/questions/7007427/does-a-valid-xml-file-require-an-xml-declaration) but it is recommended.

**Comment by pcoop** [comment]
The difficult is that "When _BPXK_AUTOCVT is ON, automatic conversion can only take place between IBM-1047 and ISO8859-1 code sets. Other CCSID pairs are not supported for automatic text conversion." ( https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbcpx01/setenv.htm )

If we want things to work reasonably naturally with _BPX_AUTOCVT=ON (rather than AUTO) we have to tag as 8859-1. Loads of stuff gets tagged as ISO-8859-1 for this reason, regardless of what the encoding actually is.

We can tag as UTF-8 if we want, just be aware that doing so can trigger other issues.

**Comment by pcoop** [comment]
The issue with the XML encoding declaration is of a similar nature. I'm not against changing the existing conventions for these things, but it seems a little odd to start doing so from within this project.

**Comment by markcocker** [comment]
> changing the existing conventions for these things

Why should `zowe cics-deploy generate bundle` be different to CICS Explorer?

**Comment by pcoop** [comment]
Take a look in the CICS installation directories. If you look through the /samples and /schemas directories (for example) you'll find that every XML file is tagged as either ISO8859-1 or IBM-1047 and just about all of them omit the optional encoding attribute. We can debate with the CICS team whether that's still a useful convention, but CICS has been following that convention for a long time.

**Comment by markcocker** [comment]
Setting [_BPXK_AUTOCVT=ALL](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbcpx01/setenv.htm) will automatically convert files tagged with UTF-8 (and other codepages) to/from local EBCDIC encoding for editing and viewing as shown below. [Steps for setting up Unicode Services](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxb200/stepus.htm) only mentions _BPXK_AUTOCVT=ALL.

However _BPXK_AUTOCVT=ON will ONLY convert between IBM-1047 and ISO8859-1 which is very limiting.

I take @pcoop point above that consistency with CICS TS installation that tags XML files with ISO8859-1 is perhaps the best approach for at the moment.

```console
$ ls -lT                 
total 16
t UTF-8       T=on  -rw-r--r--   1 COCKERM  TSOUSER      502 Apr 26 09:31 cics.xml

$ export _BPXK_AUTOCVT=ALL

$ cat cics.xml            
<manifest xmlns="http://www.ibm.com/xmlns/prod/cics/bundle" bundleVersion="1" bundleRelease="0" id="cics-nodejs-invoke" bundleMajorVer="1" bundleMinorVer="0" bundleMicroVer="0">
    <define name="cics-nodejs-invoke1" type="http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP" path="nodejsapps/cics-nodejs-invoke1.nodejsapp"></define>
    <define name="cics-nodejs-invoke2" type="http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP" path="nodejsapps/cics-nodejs-invoke2.nodejsapp"></define>
</manifest>
```
