### ISSUE TITLE
Running PUSH on a new bundle deploy with --overwrite fails as rm -r * does not work.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#106]
Undeployed existing bundle from CICS
Removing the contents of the remote bundle directory
Issuing SSH command 'rm -r *' in remote directory '/u/atkinc/pushtest/CICSMULT2_1.1.2'
Running PUSH on a new bundle deploy with --overwrite fails as rm -r * does not work.

Which it wouldn't as the directory does not exist.  This is the output.  Should the --overwrite cope with this ?

$ cd /u/atkinc/pushtest/CICSMULT2_1.1.2 && rm -r *
rm: FSUM9195 cannot unlink entry "*": EDC5129I No such file or directory.
$
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to run 'rm -r *' in remote directory '/u/atkinc/pushtest/CICSMULT2_1.1.2'. Problem is: The output from the remote command implied that an error occurred.

**Comment by pcoop** [comment]
Are you on a current build of the code? I ask as that's something that I thought we'd got working a week or so ago, not sure why it would have regressed.

**Comment by pcoop** [comment]
It's getting confused by the EDC5129I message being there too. The FSUM9195 message is being spotted and tolerated, but the EDC message causes it to think that there's something else to worry about too. This is a side effect of the fix last week to avoid over tolerating mixtures of FSUM9195 and other messages... now we're under tolerating such combinations!
