### ISSUE TITLE
Add targetdir in to cics-deploy profile

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#109]
The `zowe cics-deploy push bundle` has a required option `--targetdir` that "Specifies the target zFS location in which the CICS bundle should be created". This would typically be a common location such as /var/cicsts/CICSPLEXA/bundles where the access permissions can be maintained by the CICS system programmer - the target CICS region(s) user ID needs read access and the user id under which the deployment is being run on z/OS needs write access.

If the z/OS Provisioning Toolkit is being used to provision the CICS region, it would be under a specific mount point created for that CICS region such as /u/cicprov/mnt/CICPY000/bundles.

These scenarios suggest a developer would see the --scope and --targetdir as closely related and want to set them at the same time in the cics-deploy profile, and have `zowe cics-deploy push bundle` use them as defaults for deploying all their bundles.

**Comment by markcocker** [comment]
Thanks.

Verified build zowe-cli-cics-deploy-plugin@0.5.0-next.201905021101:
- [x]  `zowe profiles update cics-deploy` works with the optional --targetdir
- [x] `zowe profiles update cics-deploy -- help` has an example with --targetdir
- [x]  `zowe profiles create cics-deploy` works with the optional --targetdir and displays targetdir in the output

- [x] `zowe cics-deploy push bundle` with no --targetdir uses targetdir from profile
- [x] `zowe cics-deploy push bundle` with --targetdir takes preference profile

- [x] `CLIReadme.md`: zowe profiles update cics-deploy shows —targetdir as optional
- [x] `CLIReadme.md`: zowe profiles create cics-deploy shows —targetdir as optional

@ChrisAtkinson1 FYI - you may want to update automation to take advantage of having --targetdir in the profile, rather than on the push command.

**Comment by ChrisAtkinson1** [comment]
zowe-cli-cics-deploy-plugin@0.5.0-next.201905021101 for me shows...

Syntax Error:
Missing Required Option:
--targetdir (--td)

Option Description:
Specifies the target zFS location in which the CICS bundle should be created (up
to 255 characters)

When in the profile.

**Comment by ChrisAtkinson1** [comment]
Also

[31m[39mUnknown argument: targetDir
Command failed due to improper syntax
Command entered: "bright profiles create cics-deploy deploy --cicsplex N845 --cicshlq ANTZ.CICS.TS.DEV.INTEGRAT --cpsmhlq ANTZ.CICS.TS.DEV.INTEGRAT --scope JATP2402 --csdgroup NODETEST --targetDir /u/atkinc/jatptmp/N845/cicsbundles/CICSJSON"
Available commands are "zosmf-profile, tso-profile, ssh-profile, cics-deploy-profile".
Use "bright profiles create --help" to view groups, commands, and options

**Comment by markcocker** [comment]
@ChrisAtkinson1 I suspect you are not using the latest build. It was only fixed this morning. Check output from `zowe plugins install zowe-cli-cics-deploy-plugin@next`. It should include a 20190502 date stamp or later.
```
npm WARN zowe-cli-cics-deploy-plugin@0.5.0-next.201905021101 requires a peer of @zowe/cli@^3.2.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by ChrisAtkinson1** [comment]
See above it was the same timestamp as your build

zowe-cli-cics-deploy-plugin@0.5.0-next.201905021101

**Comment by markcocker** [comment]
@ChrisAtkinson1 `--targetDir /u/atkinc/jatptmp/N845/cicsbundles/CICSJSON` needs to be updated to all lower case `--targetdir`

**Comment by ChrisAtkinson1** [comment]
Aha I see
