### ISSUE TITLE
Command line help could be clearer

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#113]
To use --merge you have to use --overwrite.

I don't think the current help is very clear on this. 

Currently it is -  ( but no explanation that overwrite is needed with merge)

   --overwrite  | --ow (boolean)

      Enable or disable the ability to replace existing files within a CICS bundle.

   --merge  | --me (boolean)

      Enable or disable the ability to merge new resources into an existing CICS
      bundle manifest.

Either that or merge should not require overwrite.

**Comment by pcoop** [comment]
I've tried to explain in Issue #37 that --merge has to require --overwrite otherwise the behaviour of "--merge --overwrite false" would be the opposite of what one might reasonably expect.

**Comment by markcocker** [comment]
Back to @ChrisAtkinson1 to consider if he thinks this issue is resolved as a result of changes in #119.

**Comment by ChrisAtkinson1** [comment]
No it is not.   If we have merge needing overwrite - the command line help should say so.

**Comment by matthewpwilson** [comment]
Going to update the help as part of #37, so nothing more to do here.
