### ISSUE TITLE
When generating a bundle in an Empty folder - should it work at all ?

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#137]
When you run generate on an empty folder - should it work ?

What is the use case for creating a META-INF and cics.xml file that contains no bundle parts.  Should we treat this as an error ?

When no bundleID is specified - it is even just called Anonymous...

zowe cics-deploy generate bundle  --ow
    create : META-INF
    create : META-INF\cics.xml
Anonymous CICS Bundle generated

When you specify a bundlename or bundleversion they are added to the cics.xml correctly, but I still don't see why we allow this.

**Comment by pcoop** [comment]
When first implemented it didn't do that. Matthew was of the opinion that it should do that, so I added code accordingly. It's not unreasonable that _generate bundle_ will generate a bundle, it could be a useful starting point from which to hand edit whatever extras you want.

**Comment by markcocker** [comment]
I suggest we keep this capability. For example it may make sense to some people to generate the CICS bundle, then add your Node.js apps, then use generate again with --merge and --overwrite:
```
zowe cics-deploy generate bundle
express myExpressApp1
express myExpressApp2
zowe cics-deploy generate bundle --overwrite --merge --nodejsapp myExpressApp1 --startscript myExpressApp1/bin/www
zowe cics-deploy generate bundle --overwrite --merge --nodejsapp myExpressApp2 --startscript myExpressApp2/bin/www
```
