### ISSUE TITLE
Provide a new command to test ssh, zosmf and cics-deploy profiles

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#139]
After a user creates a cics-deploy profile they may be unsure if the options are correct for their installation. Also `cics-deploy push bundle` requires ssh and zosmf profiles to be created and be setup correctly.

The Zowe docs suggest using `zowe zosmf check status` to test the connection to z/OSMF. 

A similar `cics-deploy check status` could issue a benign SSH command (e.g. echo Hello) and submit JCL that runs DFHDPLOY to only connect to the CICSplex and then end. This would test the basic entries in all three profiles contain values that work. This command could display messages like `Testing connection using ssh profile` then `Testing connection using zosmf and cics-deploy profiles`.

Alternatively we could update the docs to suggest the reader generates and deploys a CICS bundle as a test.

**Comment by pcoop** [comment]
I like the idea of a test command. Our docs already describe how to test the zosmf and ssh profiles individually, I don't think we need to duplicate that bit.

Testing the cics-deploy profile involves three incremental stages:

1. Validate the static configuration (the HLQs and targetdir).
2. Validate that a CPSM agent is listening (and that the CMAS and SCOPE are meaningful).
3. Validate that the user has all the authorisations needed, a suitably configured .profile on USS, etc.

The first part is easy, we could easily discover a typo in the HLQs, or insufficient authorisation. The second part is a bit messier as it needs the target environment to have been provisioned, it's possible for it to be temporarily unavailable. The third part is harder, we'd have to actually deploy something... we might want a sample application to deploy.
