### ISSUE TITLE
--bundleid overrides the NODEJSAPP name from package.json

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#15]
If I have an app with a package.json in it and run the following:
```
zowe cics-deploy generate bundle --bundleId myNodeBundle
```
The generated bundle uses `myNodeBundle` for both the name of the NODEJSAPP and the bundle ID. I was expecting the name from package.json to be used for the NODEJSAPP, and just the ID to be overridden.

**Comment by matthewpwilson** [comment]
Fixed.

**Comment by matthewpwilson** [comment]
Oops, closed the wrong issue - this is not fixed yet.

**Comment by pcoop** [comment]
Interesting... I wasn't expecting this requested behaviour. I'm not sure that I have any strong opinion on this, but it seems more logical to me that as the default value of the nodejsapp is the first 32 chars of the bundleid, the bundleid value that's passed in from the user ought to be honoured in the NODEJSAPP name. If a user is supplying a bundleid value to use then that implies they have doubts over the usefulness of the value in package.json.

**Comment by matthewpwilson** [comment]
OK I'm happy to keep the existing behaviour, it's already described in the help too.
