### ISSUE TITLE
Installation instructions don't currently work

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#151]
The installation instructions here: https://ibm.github.io/zowe-cli-cics-deploy-plugin/cdp-Installation.html

won't actually work at the moment for a couple of reasons:

1. We require the `@latest` tag for Zowe cLI. I'm not sure if this has made it to the npmjs.org repo yet, but it is planned to. However, if we move to the `@lts-incremental` tag as per #121 this will not make it to npmjs.org until the next major release. I think the upshot is we'll need to add information here about configuring the brightside registry, and specify the tag to install.
2. Our plugin is not available from a public npm repo yet.

So should we add a note to this page to refer back to building the plugin from source if users want to try it now?

**Comment by markcocker** [comment]
Above PR changes the install instructions to build and install from source. Once the cics-deploy plugin is published to npm we can simplify the instructions to a single npm command.
