### ISSUE TITLE
PUSH command npm error

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#154]
Getting an error running PUSH and installing npm modules.

zowe cics-deploy push bundle --name CICSJS02 --targetdir /u/atkinc/pushtest --zosmf-profile zosmf2c2 --cics-deploy-profile deploy --ssh-profile ssh2Ckey2   --v
Making remote bundle directory '/u/atkinc/pushtest/CICSJSON_1.0.0'
Accessing contents of remote bundle directory
Uploading bundle contents to remote directory
Running 'npm install' in '/u/atkinc/pushtest/CICSJSON_1.0.0'
Issuing SSH command 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

express-parameters@ /u/atkinc/pushtest/CICSJSON_1.0.0
+-- body-parser@1.19.0
| +-- bytes@3.1.0
| +-- content-type@1.0.4
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2
| +-- http-errors@1.7.2
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.1.1
| | +-- statuses@1.5.0
| | `-- toidentifier@1.0.0
| +-- iconv-lite@0.4.24
| | `-- safer-buffer@2.1.2
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@6.7.0
| +-- raw-body@2.4.0
| | `-- unpipe@1.0.0
| `-- type-is@1.6.18
|   `-- mime-types@2.1.24
|     `-- mime-db@1.40.0
`-- express@4.10.8
  +-- accepts@1.1.4
  | +-- mime-types@2.0.14
  | | `-- mime-db@1.12.0
  | `-- negotiator@0.4.9
  +-- content-disposition@0.5.0
  +-- cookie@0.1.2
  +-- cookie-signature@1.0.5
  +-- debug@2.1.3
  | `-- ms@0.7.0
  +-- depd@1.0.1
  +-- escape-html@1.0.1
  +-- etag@1.5.1
  | `-- crc@3.2.1
  +-- finalhandler@0.3.3
  | +-- debug@2.1.3
  | | `-- ms@0.7.0
  | `-- on-finished@2.2.1
  |   `-- ee-first@1.1.0
  +-- fresh@0.2.4
  +-- media-typer@0.3.0
  +-- merge-descriptors@0.0.2
  +-- methods@1.1.1
  +-- on-finished@2.2.1
  | `-- ee-first@1.1.0
  +-- parseurl@1.3.3
  +-- path-to-regexp@0.1.3
  +-- proxy-addr@1.0.10
  | +-- forwarded@0.1.2
  | `-- ipaddr.js@1.0.5
  +-- qs@2.3.3
  +-- range-parser@1.0.3
  +-- send@0.10.1
  | +-- debug@2.1.3
  | | `-- ms@0.7.0
  | +-- depd@1.0.1
  | +-- destroy@1.0.3
  | +-- mime@1.2.11
  | +-- ms@0.6.2
  | `-- on-finished@2.1.1
  |   `-- ee-first@1.1.0
  +-- serve-static@1.7.2
  +-- type-is@1.5.7
  | `-- mime-types@2.0.14
  |   `-- mime-db@1.12.0
  +-- utils-merge@1.0.0
  `-- vary@1.0.1

npm WARN express-parameters@ No description
npm WARN express-parameters@ No repository field.
npm WARN express-parameters@ No license field.
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to run 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'. Problem is: The output from the remote command implied that an error occurred.

**Comment by ChrisAtkinson1** [comment]
Error reported without verbose is 

A problem occurred attempting to run 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install' in remote directory '/u/atkinc/jatptmp/N864/cicsbundles/CICSJSON/CICSJSON_1.0.0'. Problem is: The output from the remote command implied that an error occurred

**Comment by pcoop** [comment]
I suspect this is related to the SSH response code checking that was added at the end of last week. Presumably NPM is ending with a non-zero rc because of the Warnings, and that will need tolerating.

@ChrisPark89  - It might be good to include the rc in the error message (or otherwise log it) if my guess is correct.

**Comment by pcoop** [comment]
This might be a dependencies issue. The latest branch of zowe-cli doesn't seem to include support for SSH response codes just yet, consequently the value always comes back (at least for me) as 'undefined'. And that's not equal to zero, so the SSH command is considered to have failed.

**Comment by ChrisPark89** [comment]
Which version of zowe-cli are you using?
I think Paul is right, their latest branch from npm doesn't include the return code feature yet.

**Comment by ChrisAtkinson1** [comment]
I am using 5.5.0

Installed by npm install -g @zowe/cli

**Comment by ChrisPark89** [comment]
I found the issue.
Using cwd option didn't return the exit code correctly, where the push command uses it.

I did a new p&r to the zowe-cli repository and it's just approved.

I'll keep tracking it and let you know when it's merged to the latest.
(https://github.com/zowe/zowe-cli/pull/380)
(https://github.com/zowe/zowe-cli/pull/379)

**Comment by matthewpwilson** [comment]
The PRs have been merged so you could install Zowe CLI with `@daily`. AFAIK `@latest` is updated every two weeks.

**Comment by ChrisAtkinson1** [comment]
This is working with @daily

**Comment by markcocker** [comment]
@matthewpwilson Should we modify the install instructions at https://ibm.github.io/zowe-cli-cics-deploy-plugin/cdp-Installation.html from `@zowe/cli` to `@zowe/cli@daily` until this reaches latest?

**Comment by ChrisPark89** [comment]
@markcocker The update is on the latest(5.5.2) now. I just checked it.
