### ISSUE TITLE
Using a Zosmf profile and sshprofile with different LPAR connections caused error 

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#171]
I have a zosmf connection that connects to MV26 ( with a sysaff=MV2C)  and an sshprofile that connects to MV2C.

This causes an error for some reason on npm install.

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics-deploy push bundle --name CICSJS03 --targetdir /u/atkinc/pushtest --zosmf-profile zosmf26 --cics-deploy-profile deploy --ssh-profile ssh2Ckey  --ow --v
Making remote bundle directory '/u/atkinc/pushtest/CICSJSON_1.0.0'
Accessing contents of remote bundle directory
Undeploying bundle 'CICSJS03' from CICS
Running DFHDPLOY (UNDEPLOY), job JOB22294

15:48:58.384536 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/20 3:48pm
15:48:58.385700 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
15:48:58.387282 :  *
15:48:58.387289 :  SET CICSPLEX(CAPLEX);
15:49:00.407680 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
15:49:02.426484 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
15:49:02.445937 :
15:49:02.445959 :  *
15:49:02.445966 :  UNDEPLOY BUNDLE(CICSJS03)
15:49:02.445971 :         SCOPE(CALMAS1)
15:49:02.445975 :         STATE(DISCARDED)
15:49:02.445979 :         CSDGROUP(NODETEST);
15:49:02.446652 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
15:49:09.496459 :  DFHRL2093I BUNDLE(CICSJS03) found in SCOPE(CALMAS1).
15:49:09.496514 :  DFHRL2129I BUNDLE(CICSJS03) state is INSTALLED on 1 CICS regions in SCOPE(CALMAS1).
15:49:09.496548 :  DFHRL2129I BUNDLE(CICSJS03) state is DISABLED on 1 CICS regions in SCOPE(CALMAS1).
15:49:09.496578 :  DFHRL2054I Setting BUNDLE state to DISABLED.
15:49:13.527472 :  DFHRL2042I Discarding BUNDLE(CICSJS03).
15:49:22.583172 :  DFHRL2077I BUNDLE(CICSJS03) has been discarded from SCOPE(CALMAS1).
15:49:22.704324 :  DFHRL2114I Bundle definition for BUNDLE(CICSJS03) in CSDGROUP(NODETEST) has been removed in system(CALMAS1 ).
15:49:22.704367 :  DFHRL2037I UNDEPLOY command successful.
15:49:22.706664 :
15:49:22.706697 :  DFHRL2007I Processing complete.
15:49:22.710274 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Undeploy complete
Running 'npm uninstall *' in '/u/atkinc/pushtest/CICSJSON_1.0.0'
Issuing SSH command 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && if [ -d "node_modules" ] && [ "$(ls node_modules)" ]; then npm uninstall `ls -1 node_modules | tr '/
' ' '`; fi' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

<dules)" ]; then npm uninstall `ls -1 node_modules | tr '/
> ' ' '`; fi
- mime-db@1.12.0 node_modules/accepts/node_modules/mime-db
- mime-types@2.0.14 node_modules/accepts/node_modules/mime-types
- bytes@3.1.0 node_modules/bytes
- content-disposition@0.5.0 node_modules/content-disposition
- content-type@1.0.4 node_modules/content-type
- cookie@0.1.2 node_modules/cookie
- cookie-signature@1.0.5 node_modules/cookie-signature
- crc@3.2.1 node_modules/crc
- depd@1.1.2 node_modules/depd
- destroy@1.0.3 node_modules/destroy
- ee-first@1.1.1 node_modules/ee-first
- escape-html@1.0.1 node_modules/escape-html
- etag@1.5.1 node_modules/etag
- depd@1.0.1 node_modules/express/node_modules/depd
- ee-first@1.1.0 node_modules/express/node_modules/ee-first
- mime-db@1.12.0 node_modules/express/node_modules/mime-db
- mime-types@2.0.14 node_modules/express/node_modules/mime-types
- ms@0.7.0 node_modules/express/node_modules/ms
- debug@2.1.3 node_modules/express/node_modules/debug
- on-finished@2.2.1 node_modules/express/node_modules/on-finished
- qs@2.3.3 node_modules/express/node_modules/qs
- ee-first@1.1.0 node_modules/finalhandler/node_modules/ee-first
- ms@0.7.0 node_modules/finalhandler/node_modules/ms
- debug@2.1.3 node_modules/finalhandler/node_modules/debug
- on-finished@2.2.1 node_modules/finalhandler/node_modules/on-finished
- finalhandler@0.3.3 node_modules/finalhandler
- forwarded@0.1.2 node_modules/forwarded
- fresh@0.2.4 node_modules/fresh
- inherits@2.0.3 node_modules/inherits
- ipaddr.js@1.0.5 node_modules/ipaddr.js
- media-typer@0.3.0 node_modules/media-typer
- type-is@1.5.7 node_modules/express/node_modules/type-is
- merge-descriptors@0.0.2 node_modules/merge-descriptors
- methods@1.1.1 node_modules/methods
- mime@1.2.11 node_modules/mime
- mime-db@1.40.0 node_modules/mime-db
- mime-types@2.1.24 node_modules/mime-types
- ms@2.0.0 node_modules/ms
- debug@2.6.9 node_modules/debug
- negotiator@0.4.9 node_modules/negotiator
- accepts@1.1.4 node_modules/accepts
- on-finished@2.3.0 node_modules/on-finished
- parseurl@1.3.3 node_modules/parseurl
- path-to-regexp@0.1.3 node_modules/path-to-regexp
- proxy-addr@1.0.10 node_modules/proxy-addr
- qs@6.7.0 node_modules/qs
- range-parser@1.0.3 node_modules/range-parser
- safer-buffer@2.1.2 node_modules/safer-buffer
- iconv-lite@0.4.24 node_modules/iconv-lite
- ms@0.7.0 node_modules/send/node_modules/debug/node_modules/ms
- debug@2.1.3 node_modules/send/node_modules/debug
- depd@1.0.1 node_modules/send/node_modules/depd
- ee-first@1.1.0 node_modules/send/node_modules/ee-first
- ms@0.6.2 node_modules/send/node_modules/ms
- on-finished@2.1.1 node_modules/send/node_modules/on-finished
- send@0.10.1 node_modules/send
- setprototypeof@1.1.1 node_modules/setprototypeof
- statuses@1.5.0 node_modules/statuses
- toidentifier@1.0.0 node_modules/toidentifier
- http-errors@1.7.2 node_modules/http-errors
- type-is@1.6.18 node_modules/type-is
- unpipe@1.0.0 node_modules/unpipe
- raw-body@2.4.0 node_modules/raw-body
- utils-merge@1.0.0 node_modules/utils-merge
- serve-static@1.7.2 node_modules/serve-static
- vary@1.0.1 node_modules/vary
- body-parser@1.19.0 node_modules/body-parser
- express@4.10.8 node_modules/express
npm WARN express-parameters@ No description
npm WARN express-parameters@ No repository field.
npm WARN express-parameters@ No license field.

Removing contents of remote bundle directory
Issuing SSH command 'if [ "$(ls)" ]; then rm -r *; fi' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

$ cd /u/atkinc/pushtest/CICSJSON_1.0.0 && if [ "$(ls)" ]; then rm -r *; fi

Uploading bundle contents to remote directory
Running 'npm install' in '/u/atkinc/pushtest/CICSJSON_1.0.0'
Issuing SSH command 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

<="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install
npm ERR! OS/390 25.00
npm ERR! argv "/TMP202/usr/lpp/IBM/cnj/IBM/node-v6.16.0-os390-s390x/bin/node" "/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin/npm" "install"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! file /u/atkinc/pushtest/CICSJSON_1.0.0/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '#' at 1:1
npm ERR! #
npm ERR! ^
npm ERR! File: /u/atkinc/pushtest/CICSJSON_1.0.0/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /u/atkinc/pushtest/CICSJSON_1.0.0/npm-debug.log

Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to run 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'. Problem is: The output from the remote command implied that an error occurred, return code 1.

**Comment by pcoop** [comment]
We do document that mixing ids and hostnames will result in unpredictable results, but this is particularly peculiar ("_It is recommended that you use the same user ID and host name to connect with SSH as is used in the z/OSMF profile, failure to do so results in undefined behaviour._").

I think npm is complaining that package.json contains garbage, are you able to look at it yourself? Does it look garbled? I'm wondering if the auto convert options are different on the two systems such that it works for one and not the other. Maybe.

Another thought: do file-system changes made on MV26 instantly propagate to be available on MV2C? If there's a delay as the caches refresh then maybe we were just too quick to switch from one context to the other.

**Comment by ChrisAtkinson1** [comment]
The package.json looks fine to me

`{
  "name": "express-parameters",
  "main": "cicsjson.js",
  "dependencies": {
    "body-parser": "^1.18.3",
    "express": "~4.10.2"
  }
}`

The sshprofile - was the one I normally use to upload.  I changed the zosmf profile to the different system.  But pointed it to the 2C location in the SYSAFF as that's where my systems are running.

**Comment by ChrisAtkinson1** [comment]
I assume that as the sshprofile was pointed to 2C that's where the upload and npm would run ?

**Comment by pcoop** [comment]
The upload is done through zosMF, not SSH.

**Comment by ChrisAtkinson1** [comment]
The reverse - 

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics-deploy push bundle --name CICSJS03 --targetdir /u/atkinc/pushtest --zosmf-profile zosmf2c --cics-deploy-profile deploy --ssh-profile ssh26key  --ow --v
Making remote bundle directory '/u/atkinc/pushtest/CICSJSON_1.0.0'
Accessing contents of remote bundle directory
Undeploying bundle 'CICSJS03' from CICS
Running DFHDPLOY (UNDEPLOY), job JOB26179

11:11:03.968387 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/21 11:11am
11:11:03.969368 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
11:11:03.970605 :  *
11:11:03.970612 :  SET CICSPLEX(CAPLEX);
11:11:05.990934 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
11:11:08.001655 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
11:11:08.018487 :
11:11:08.018507 :  *
11:11:08.018513 :  UNDEPLOY BUNDLE(CICSJS03)
11:11:08.018518 :         SCOPE(CALMAS1)
11:11:08.018522 :         STATE(DISCARDED)
11:11:08.018526 :         CSDGROUP(NODETEST);
11:11:08.019182 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
11:11:13.059754 :  DFHRL2082I BUNDLE(CICSJS03) in SCOPE(CALMAS1) does not exist.
11:11:13.196051 :  DFHRL2112I Bundle definition for BUNDLE(CICSJS03) in CSDGROUP(NODETEST) does not exist in system(CALMAS1 ).
11:11:13.196095 :  DFHRL2037I UNDEPLOY command successful.
11:11:13.197020 :
11:11:13.197050 :  DFHRL2007I Processing complete.
11:11:13.200665 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Undeploy complete
Running 'npm uninstall *' in '/u/atkinc/pushtest/CICSJSON_1.0.0'
Issuing SSH command 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && if [ -d "node_modules" ] && [ "$(ls node_modules)" ]; then npm uninstall `ls -1 node_modules | tr '/
' ' '`; fi' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

<dules)" ]; then npm uninstall `ls -1 node_modules | tr '/
> ' ' '`; fi

Removing contents of remote bundle directory
Issuing SSH command 'if [ "$(ls)" ]; then rm -r *; fi' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

$ cd /u/atkinc/pushtest/CICSJSON_1.0.0 && if [ "$(ls)" ]; then rm -r *; fi

Uploading bundle contents to remote directory
Running 'npm install' in '/u/atkinc/pushtest/CICSJSON_1.0.0'
Issuing SSH command 'export PATH="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install' in remote directory '/u/atkinc/pushtest/CICSJSON_1.0.0'

<="$PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install
express-parameters@ /u/atkinc/pushtest/CICSJSON_1.0.0
+-- body-parser@1.19.0
| +-- bytes@3.1.0
| +-- content-type@1.0.4
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2
| +-- http-errors@1.7.2
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.1.1
| | +-- statuses@1.5.0
| | `-- toidentifier@1.0.0
| +-- iconv-lite@0.4.24
| | `-- safer-buffer@2.1.2
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@6.7.0
| +-- raw-body@2.4.0
| | `-- unpipe@1.0.0
| `-- type-is@1.6.18
|   `-- mime-types@2.1.24
|     `-- mime-db@1.40.0
`-- express@4.10.8
  +-- accepts@1.1.4
  | +-- mime-types@2.0.14
  | | `-- mime-db@1.12.0
  | `-- negotiator@0.4.9
  +-- content-disposition@0.5.0
  +-- cookie@0.1.2
  +-- cookie-signature@1.0.5
  +-- debug@2.1.3
  | `-- ms@0.7.0
  +-- depd@1.0.1
  +-- escape-html@1.0.1
  +-- etag@1.5.1
  | `-- crc@3.2.1
  +-- finalhandler@0.3.3
  | +-- debug@2.1.3
  | | `-- ms@0.7.0
  | `-- on-finished@2.2.1
  |   `-- ee-first@1.1.0
  +-- fresh@0.2.4
  +-- media-typer@0.3.0
  +-- merge-descriptors@0.0.2
  +-- methods@1.1.1
  +-- on-finished@2.2.1
  | `-- ee-first@1.1.0
  +-- parseurl@1.3.3
  +-- path-to-regexp@0.1.3
  +-- proxy-addr@1.0.10
  | +-- forwarded@0.1.2
  | `-- ipaddr.js@1.0.5
  +-- qs@2.3.3
  +-- range-parser@1.0.3
  +-- send@0.10.1
  | +-- debug@2.1.3
  | | `-- ms@0.7.0
  | +-- depd@1.0.1
  | +-- destroy@1.0.3
  | +-- mime@1.2.11
  | +-- ms@0.6.2
  | `-- on-finished@2.1.1
  |   `-- ee-first@1.1.0
  +-- serve-static@1.7.2
  +-- type-is@1.5.7
  | `-- mime-types@2.0.14
  |   `-- mime-db@1.12.0
  +-- utils-merge@1.0.0
  `-- vary@1.0.1

npm WARN express-parameters@ No description
npm WARN express-parameters@ No repository field.
npm WARN express-parameters@ No license field.

Deploying bundle 'CICSJS03' to CICS
Running DFHDPLOY (DEPLOY), job JOB26183

11:11:30.875420 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/21 11:11am
11:11:30.876210 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
11:11:30.877558 :  *
11:11:30.877565 :  SET CICSPLEX(CAPLEX);
11:11:32.902513 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
11:11:34.916807 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
11:11:34.933787 :
11:11:34.933812 :  *
11:11:34.933818 :  DEPLOY BUNDLE(CICSJS03)
11:11:34.933823 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
11:11:34.933827 :         SCOPE(CALMAS1)
11:11:34.933831 :         STATE(ENABLED)
11:11:34.933835 :         CSDGROUP(NODETEST);
11:11:34.940617 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
11:11:42.999193 :  DFHRL2051I Creating BUNDLE definition on the CSD in system(CALMAS1 ).
11:11:43.127021 :  DFHRL2049I Creating BUNDLE definition.
11:11:43.150771 :  DFHRL2024I BUNDLE definition(CICSJS03) VERSION(1) successfully created.
11:11:44.155657 :  DFHRL2052I Installing BUNDLE definition.
11:11:44.156146 :  DFHRL2131I Waiting for BUNDLE(CICSJS03) to be installed in active regions in SCOPE(CALMAS1).
11:12:00.255717 :  DFHRL2130I BUNDLE(CICSJS03) installed in 1 of 1 regions in SCOPE(CALMAS1).
11:12:00.255774 :  DFHRL2054I Setting BUNDLE state to ENABLED.
11:12:04.301121 :  DFHRL2012I DEPLOY command completed successfully.
11:12:04.305757 :
11:12:04.305795 :  DFHRL2007I Processing complete.
11:12:04.313226 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Deploy complete
PUSH operation completed.

**Comment by ChrisAtkinson1** [comment]
The SYSAFF is in my deploy profile.

`cicsplex: CAPLEX
scope: CALMAS1
csd-group: NODETEST
cics-hlq: ANTZ.CICS.TS.DEV.INTEGRAT
cpsm-hlq: ANTZ.CICS.TS.DEV.INTEGRAT
job-card: '//DFHDPLOY JOB DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT,SYSAFF=MV2C'`

**Comment by pcoop** [comment]
We could add validation to check that the --host in the zosMF and SSH profiles have the same value, and refuse to run if they're different (or at least tell the user that there might be a problem). We could do the same with the --user value too.

**Comment by ChrisAtkinson1** [comment]
The user was the same here, but that may well be more of a problem.

Seems odd it works one - way and not the other.

**Comment by matthewpwilson** [comment]
This feels like it could be a legitimate configuration to me.  I think we need to understand what went wrong.  Can you try running `npm install` manually for the failing case please Chris?  Also would be interesting to compare the tagging of package.json in each case.

**Comment by ChrisAtkinson1** [comment]
Manually running on the failed version is fine.

  +-- serve-static@1.7.2
  +-- type-is@1.5.7
  | `-- mime-types@2.0.14
  |   `-- mime-db@1.12.0
  +-- utils-merge@1.0.0
  `-- vary@1.0.1

npm WARN express-parameters@ No description
npm WARN express-parameters@ No repository field.
npm WARN express-parameters@ No license field.

**Comment by ChrisAtkinson1** [comment]
t ISO8859-1   T=on  cicsjson.js
t IBM-1047    T=on  cicsjson.profile
- untagged    T=off npm-debug.log
t ISO8859-1   T=on  package.json
- untagged    T=off tags

**Comment by ChrisPark89** [comment]
@ChrisAtkinson1 Have you found what causes this? It looks like it's an encoding issue.
Could you run it with ssh profile to connect to MV26 as well, so both zosmf and ssh to connect to MV26.

**Comment by ChrisAtkinson1** [comment]
Seems to work now

26 & 26 - 
[ssh26zosmf26.txt](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3275794/ssh26zosmf26.txt)

26 & 2c - 
[zosmf26ssh2c.txt](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3275807/zosmf26ssh2c.txt)
