### ISSUE TITLE
return code not documented for cics-deploy plugin commands

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#175]
The cics-deploy plugin sets RC=1 when there are failures. Scripts will generally rely on the RC to know when a command has worked or not. We need to document these values for each command, either in the description or ask Zowe CLI team to extend imperative to provide a new section for them.

For example:
```console
zowe cics-deploy push bundle --name Express || echo "RC=$?"
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = The target directory does not exist, consider creating it by issuing: 
zowe zos-uss issue ssh "mkdir -p /u/cicprov/mnt/CICPY000/bundles"
RC=1
```

**Comment by tasha-m-k** [comment]
@markcocker is this generated help, or do we need something in the docs too?

**Comment by markcocker** [comment]
I suggest the return codes should be part of the command line help. We will need to put this in the upfront description.

I will have raised an issue against Zowe CLI team https://github.com/zowe/zowe-cli/issues/436 and once that is resolved we can follow its lead is where/how to document return codes.

**Comment by matthewpwilson** [comment]
We would also need to change the code to actually issue distinct return codes for different error scenarios.

**Comment by markcocker** [comment]
@matthewpwilson I was not suggesting we need new return codes, merely too document the 0 and 1 return codes already set.

**Comment by matthewpwilson** [comment]
Ah OK. We wondering whether it would be useful for automation to have distinct return codes for failures in each step of a `push`. Then it could decide what backout actions were needed.
