### ISSUE TITLE
Release branch & deployment automation

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#189]
We need to set a release branch. When code is pushed to the release branch, we should build, test and then publish to npmjs.org.
The release branch should be protected so that a PR and review is required.

**Comment by ChrisPark89** [comment]
- **dev**: our main dev branch, which will work with Zowe CLI @lts-incremental. It will be built, tested and deployed to internal artifactory regularly.
- **master**: our release branch, which will work with Zowe CLI @lts-incremental. We'll merge code into here from release branch. Only merge commits should be allowed.
- **release**: temporary branch based on dev, which will be merged into master. The version in package.json should be updated, if new deployment is needed in npmjs.org.
- **zowe-dev**: a branch which works with Zowe CLI@daily so we can test our changes to work with their upcoming versions.

**Comment by ChrisPark89** [comment]
Merged into `dev`
