### ISSUE TITLE
Need to suppressed the profile warnings.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#203]
When the userid in one profile is upper cased and in another uppercase.

Eg

WARNING: ssh profile --user value 'user' does not match zosmf value 'USER'.
WARNING: cics profile --user value 'user' does not match zosmf value 'USER'.

Also there is a warning for profile value being in a profile deploy - but not the cics profile ?

Eg
WARNING: cics profile --cics-plex value 'undefined' does not match --cicsplex value 'CAPLEX'

**Comment by pcoop** [comment]
I'm pretty sure I fixed both of them yesterday... the fix should have gone live already this morning.

**Comment by ChrisAtkinson1** [comment]
I'll update then

**Comment by ChrisAtkinson1** [comment]
Fixed
