### ISSUE TITLE
Should we suppress output if the bundle goes DISABLED ?

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#206]
In the test plan there is this.

Make sure output is suppressed if there is nothing valuable in it
eg. BUNDLE failed to install or enable

On DISABLE it currently does - However I think this is acceptable.

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics-deploy push bundle --name CICSJS02 --targetdir /u/atkinc/pushtest --zosmf-profile zosmf2c --cics-deploy-profile deploy --ssh-profile ssh2Ckey   --ow --targetState DISABLED
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879

NODEJSAPP resources for Bundle 'CICSJS02' in Scope 'CALMAS1':
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879

NODEJSAPP resources for Bundle 'CICSJS02' in Scope 'CALMAS1':
CICS NODEJSAPP resource 'CICSJSON' is in 'DISABLED' state in region 'CALMAS1' with process id '0'.
  stdout: <not available>
  stderr: <not available>
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879

NODEJSAPP resources for Bundle 'CICSJS02' in Scope 'CALMAS1':
CICS NODEJSAPP resource 'CICSJSON' is in 'DISABLED' state in region 'CALMAS1' with process id '0'.
  stdout: <not available>
  stderr: <not available>
PUSH operation completed.

**Comment by pcoop** [comment]
It's possible that the output files exist and have useful information in them even if the Bundle does end up disabled. For example, a Node.js application could start and almost instantly run to completion writing something to stdout in the process.

If the filenames aren't set then yeah, we could perhaps suppress the output (whilst tolerating the possibility that they're set in one region and not in another); but doing so based only on the state of the Bundle would be wrong.

**Comment by markcocker** [comment]
Perhaps suppress "stdout:" and "stderr:" lines when there are no values?

**Comment by pcoop** [comment]
What is our preferred output in this scenario:

1. Just suppress the stdout/stderr lines:

    Regions in scope 'CALMAS1' of CICSplex 'CAPLEX':
    Applid: CALMAS1 jobname: CALMAS1 jobid: JOB73879
    
    NODEJSAPP resources for bundle 'CICSJS02' in scope 'CALMAS1':
    NODEJSAPP resource 'CICSJSON' is in 'DISABLED' state in region 'CALMAS1' with process id '0'.

2. Add a suffix to explain why the output is missing:

    Regions in scope 'CALMAS1' of CICSplex 'CAPLEX':
    Applid: CALMAS1 jobname: CALMAS1 jobid: JOB73879
    
    NODEJSAPP resources for bundle 'CICSJS02' in scope 'CALMAS1':
    NODEJSAPP resource 'CICSJSON' is in 'DISABLED' state in region 'CALMAS1' with process id '0'.
        Stdout/Stderr are not available.

3. The current behaviour:

    Regions in scope 'CALMAS1' of CICSplex 'CAPLEX':
    Applid: CALMAS1 jobname: CALMAS1 jobid: JOB73879
    
    NODEJSAPP resources for bundle 'CICSJS02' in scope 'CALMAS1':
    NODEJSAPP resource 'CICSJSON' is in 'DISABLED' state in region 'CALMAS1' with process id '0'.
        Stdout: &lt;not available&gt;
        Stderr: &lt;not available&gt;

4. Something else?

**Comment by ChrisAtkinson1** [comment]
I'd vote for option 3.

**Comment by matthewpwilson** [comment]
I believe this is fixed

**Comment by ChrisAtkinson1** [comment]
Done
