### ISSUE TITLE
Duplicate logging of CICS Regions in Scope

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#207]
The report duplicated the CICS Regions in Scope - I have one.  It's listed twice.
Eg
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879

**Comment by ChrisAtkinson1** [comment]
Even more horrible when there is a duplicate bundle - there's several outputs from DFHDPLY for the same thing.

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics-deploy push bundle --name CICSJS03 --targetdir /u/atkinc/pushtest --zosmf-profile zosmf2c --cics-deploy-profile deploy --ssh-profile ssh2Ckey   --ow
14:56:41.871271 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/31 2:56pm
14:56:41.872218 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
14:56:41.873716 :  *
14:56:41.873726 :  SET CICSPLEX(CAPLEX);
14:56:43.902405 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
14:56:45.916217 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
14:56:45.934983 :
14:56:45.935002 :  *
14:56:45.935010 :  DEPLOY BUNDLE(CICSJS03)
14:56:45.935015 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
14:56:45.935019 :         SCOPE(CALMAS1)
14:56:45.935023 :         STATE(ENABLED)
14:56:45.935027 :         CSDGROUP(NODETEST);
14:56:45.940716 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
14:56:56.028602 :  DFHRL2105E BUNDLE(CICSJS03) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJS02).
14:56:56.028661 :  DFHRL2055I Errors have occurred, processing terminated.
14:56:56.033561 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

14:56:41.871271 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/31 2:56pm
14:56:41.872218 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
14:56:41.873716 :  *
14:56:41.873726 :  SET CICSPLEX(CAPLEX);
14:56:43.902405 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
14:56:45.916217 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
14:56:45.934983 :
14:56:45.935002 :  *
14:56:45.935010 :  DEPLOY BUNDLE(CICSJS03)
14:56:45.935015 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
14:56:45.935019 :         SCOPE(CALMAS1)
14:56:45.935023 :         STATE(ENABLED)
14:56:45.935027 :         CSDGROUP(NODETEST);
14:56:45.940716 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
14:56:56.028602 :  DFHRL2105E BUNDLE(CICSJS03) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJS02).
14:56:56.028661 :  DFHRL2055I Errors have occurred, processing terminated.
14:56:56.033561 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
14:56:41.871271 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/31 2:56pm
14:56:41.872218 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
14:56:41.873716 :  *
14:56:41.873726 :  SET CICSPLEX(CAPLEX);
14:56:43.902405 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
14:56:45.916217 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
14:56:45.934983 :
14:56:45.935002 :  *
14:56:45.935010 :  DEPLOY BUNDLE(CICSJS03)
14:56:45.935015 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
14:56:45.935019 :         SCOPE(CALMAS1)
14:56:45.935023 :         STATE(ENABLED)
14:56:45.935027 :         CSDGROUP(NODETEST);
14:56:45.940716 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
14:56:56.028602 :  DFHRL2105E BUNDLE(CICSJS03) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJS02).
14:56:56.028661 :  DFHRL2055I Errors have occurred, processing terminated.
14:56:56.033561 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879
14:56:41.871271 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/31 2:56pm
14:56:41.872218 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
14:56:41.873716 :  *
14:56:41.873726 :  SET CICSPLEX(CAPLEX);
14:56:43.902405 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
14:56:45.916217 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
14:56:45.934983 :
14:56:45.935002 :  *
14:56:45.935010 :  DEPLOY BUNDLE(CICSJS03)
14:56:45.935015 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
14:56:45.935019 :         SCOPE(CALMAS1)
14:56:45.935023 :         STATE(ENABLED)
14:56:45.935027 :         CSDGROUP(NODETEST);
14:56:45.940716 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
14:56:56.028602 :  DFHRL2105E BUNDLE(CICSJS03) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJS02).
14:56:56.028661 :  DFHRL2055I Errors have occurred, processing terminated.
14:56:56.033561 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879
For further information on the state of your NODEJSAPP resources, consider running the following command:

zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJS03" --cics-plex CAPLEX
14:56:41.871271 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/31 2:56pm
14:56:41.872218 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
14:56:41.873716 :  *
14:56:41.873726 :  SET CICSPLEX(CAPLEX);
14:56:43.902405 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
14:56:45.916217 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
14:56:45.934983 :
14:56:45.935002 :  *
14:56:45.935010 :  DEPLOY BUNDLE(CICSJS03)
14:56:45.935015 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
14:56:45.935019 :         SCOPE(CALMAS1)
14:56:45.935023 :         STATE(ENABLED)
14:56:45.935027 :         CSDGROUP(NODETEST);
14:56:45.940716 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
14:56:56.028602 :  DFHRL2105E BUNDLE(CICSJS03) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJS02).
14:56:56.028661 :  DFHRL2055I Errors have occurred, processing terminated.
14:56:56.033561 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879
For further information on the state of your NODEJSAPP resources, consider running the following command:

zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJS03" --cics-plex CAPLEX
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = DFHDPLOY stopped processing for jobid JOB74481 due to an error.

**Comment by pcoop** [comment]
Yup, that's the scroll bar issue again. If you run in --verbose mode then there's no scroll bar and everything is issued once; with the scrollbar output to the screen can get redrawn on a regular basis.

**Comment by pcoop** [comment]
Looking at that output, it appears that the scroll bar is redrawing the entire screen each time any console message is written, regardless of how long that message is.

So... if we were to buffer up multi-line messages and issue them all as one longer line, that would significantly reduce the impact from the scroll-bar being weird. That might be worth a go.

**Comment by ChrisAtkinson1** [comment]
Oddly - the --verbose option means it's only logged once!

npm WARN express-parameters@ No description
npm WARN express-parameters@ No repository field.
npm WARN express-parameters@ No license field.

Deploying bundle 'CICSJS03' to CICS
Running DFHDPLOY (DEPLOY), jobid JOB74554

15:24:14.439941 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/05/31 3:24pm
15:24:14.440697 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
15:24:14.442114 :  *
15:24:14.442122 :  SET CICSPLEX(CAPLEX);
15:24:16.461796 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
15:24:18.477038 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
15:24:18.494371 :
15:24:18.494389 :  *
15:24:18.494396 :  DEPLOY BUNDLE(CICSJS03)
15:24:18.494401 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
15:24:18.494405 :         SCOPE(CALMAS1)
15:24:18.494411 :         STATE(ENABLED)
15:24:18.494414 :         CSDGROUP(NODETEST);
15:24:18.498619 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
15:24:28.564789 :  DFHRL2105E BUNDLE(CICSJS03) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJS02).
15:24:28.564865 :  DFHRL2055I Errors have occurred, processing terminated.
15:24:28.570084 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Deploy ended with errors
Gathering Scope information
Querying Regions in Scope over CMCI
CICS Regions in Scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB73879
Gathering Node.js diagnostics
Querying NODEJSAPP resources over CMCI
For further information on the state of your NODEJSAPP resources, consider running the following command:

zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJS03" --cics-plex CAPLEX
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = DFHDPLOY stopped processing for jobid JOB74554 due to an error.

**Comment by matthewpwilson** [comment]
@ChrisAtkinson1 can you confirm this is fixed please
