### ISSUE TITLE
The node log files are listed as a Path - but the system they are on is not.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#208]
The log files are reported eg

NODEJSAPP resources for Bundle 'CICSJS02' in Scope 'CALMAS1':
CICS NODEJSAPP resource 'CICSJSON' is in 'ENABLED' state in region 'CALMAS1' with process id '65840'.
  stdout: /u/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190531.T140207.stdout
  stderr: /u/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190531.T140207.stderr

However I don't know from the CLI without diving into my profile what system they reside on.

Should they get the host they reside on ?

**Comment by pcoop** [comment]
I'm not sure I follow... what do you want to have changed? Do you want the hostname for the CMCI connection printed out?

What we're displaying here is the same information you can see with CEMT or Explorer. Is the information insufficient in those scenarios too?

**Comment by markcocker** [comment]
Once a push command had completed, I would likely:
* Copy the directory path, switch to the VSC zowe extension view, find the UNIX SYSTEM SERVICES (USS) pane, and click on the search icon next to the zosmf profile I used to do the push, paste in the directory path, hit enter, find the file, and click to view it. However there is a bug in that you can't refresh the file to see changes.
* Or CLI to download the file:
   `zowe zos-files download uss-file "/u/cicprov/mnt/CICPY00K/workdir/CICPY00K/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T182206.stdout"`
* Or CLI to view:
   `zowe zos-uss issue ssh "cat /u/cicprov/mnt/CICPY00K/workdir/CICPY00K/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T182206.stdout"`
* Or CLI to view and watch for new updates:
   `zowe zos-uss issue ssh "tail -f /u/cicprov/mnt/CICPY00K/workdir/CICPY00K/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T182206.stdout"`

In each of those cases I don't need too know the host, rather the zosmf profile name. As the user would have specified this in ` --zosmf-profile ` option or used their default, I think it acceptable they should also do the same to view the file using one of the techniques above.

@ChrisAtkinson1 If you are ok with the above, I can update the doc to highlight these as "next steps" in the "Deploying your first Node.js app" tutorial.

**Comment by matthewpwilson** [comment]
Triage:  Suggest adding 'MVSSYSNAME value from REGION to summary table

**Comment by markcocker** [comment]
Assigning to myself to update getting started tutorial.

**Comment by markcocker** [comment]
@ChrisAtkinson1 I believe this issue has now been addressed in PRs #255 and #256.

**Comment by ChrisAtkinson1** [comment]
Yes closing
