### ISSUE TITLE
Output messages need to use consistent casing, punctuation

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#210]
Also sometimes terms are prefixed with "CICS". For example see:
```
Deploy complete
Gathering Scope information
Querying Regions in Scope over CMCI
CICS Regions in Scope 'mac' of CICSplex 'ZOSPTINT':
   Applid: CICPY00K   jobname: CICPY00K   jobid: STC74580
   Applid: CICPY000   jobname: CICPY000   jobid: STC74578
Gathering Node.js diagnostics
Querying NODEJSAPP resources over CMCI

NODEJSAPP resources for Bundle 'INVOKE' in Scope 'mac':
CICS NODEJSAPP resource 'cics-nodejs-invoke' is in 'ENABLED' state in region 'CICPY00K' with process id '66778'.
  stdout: /u/cicprov/mnt/CICPY00K/workdir/CICPY00K/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T144922.stdout
  stderr: /u/cicprov/mnt/CICPY00K/workdir/CICPY00K/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T144922.stderr
CICS NODEJSAPP resource 'cics-nodejs-invoke' is in 'ENABLED' state in region 'CICPY000' with process id '66750'.
  stdout: /u/cicprov/mnt/CICPY000/workdir/CICPY000/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T144922.stdout
  stderr: /u/cicprov/mnt/CICPY000/workdir/CICPY000/cics-nodejs-invoke/cics-nodejs-invoke/D20190531.T144922.stderr
PUSH operation completed.
```

Suggest changing output:
1. `Gathering Scope information` to
   `Gathering scope information`
2. `Querying Regions in Scope over CMCI` to
`Querying regions in scope over CMCI`
3. `CICS Regions in Scope 'mac' of CICSplex 'ZOSPTINT':` to
   `Regions in scope 'mac' of CICSplex 'ZOSPTINT':`
4. `NODEJSAPP resources for Bundle 'INVOKE' in Scope 'mac':` to
   `NODEJSAPP resources for bundle 'INVOKE' in Scope 'mac':`
5. `CICS NODEJSAPP resource 'cics-nodejs-invoke' is in 'ENABLED' state in region 'CICPY00K' with process id '66778'.` to
   `NODEJSAPP resource 'cics-nodejs-invoke' is in 'ENABLED' state in region 'CICPY00K' with process id '66778'.`
6. `PUSH operation completed.` to
   `PUSH operation completed`
7. From online help:
   `CICS System, or CICS System Group` to
   `CICS region, or CICS system group`

There may be other similar messages.

**Comment by pcoop** [comment]
I've put a pull request together to do most of this, it's just item 7 in the list that I've left off because our text already matches what's in the CICS Knowledge Center ( https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.3.0/com.ibm.cics.ts.applicationprogramming.doc/topics/dfhdploy_command_deploybund.html ).

**Comment by markcocker** [comment]
Thanks. Verified changes 1-6.
Regarding point 7, ok I'll raise the inconsistencies in casing in the KC elsewhere.
