### ISSUE TITLE
Suggestion to run cmci request for a duplicate bundle should point to the original one

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#216]
If I try to push a bundle - where the bundle id is already installed in a CICS region - the PUSH command will return this debug output.

Regions in scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB80342
For further information on the state of your NODEJSAPP resources, consider running the following command:

zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJSO2" --cics-plex CAPLEX
15:36:07.572727 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/06/03 3:36pm
15:36:07.573653 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
15:36:07.575175 :  *
15:36:07.575190 :  SET CICSPLEX(CAPLEX);
15:36:09.596552 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
15:36:11.608476 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
15:36:11.626371 :
15:36:11.626388 :  *
15:36:11.626394 :  DEPLOY BUNDLE(CICSJSO2)
15:36:11.626400 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
15:36:11.626404 :         SCOPE(CALMAS1)
15:36:11.626408 :         STATE(ENABLED)
15:36:11.626412 :         CSDGROUP(NODETEST);
15:36:11.636841 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
**15:36:21.722614 :  DFHRL2105E BUNDLE(CICSJSO2) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJSON).**
15:36:21.722674 :  DFHRL2055I Errors have occurred, processing terminated.
15:36:21.728020 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Regions in scope 'CALMAS1' of CICSplex 'CAPLEX':
   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB80342
For further information on the state of your NODEJSAPP resources, consider running the following command:

**zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJSO2" --cics-plex CAPLEX**
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = DFHDPLOY stopped processing for jobid JOB81012 due to an error.

The error is shown by DFHDPLOY as a bundle already being deployed with the same name.  It suggests running a CMCI command against the bundle that did not deploy.  Running the will always get 1027 (NODATA) as it did not INSTALL.

Eg

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJSO2" --cics-plex CAPLEX
Command Error:
Did not receive the expected response from CMCI REST API.
response:
  xmlns:              http://www.ibm.com/xmlns/prod/CICS/smw2int
  xmlns:xsi:          http://www.w3.org/2001/XMLSchema-instance
  xsi:schemaLocation: http://www.ibm.com/xmlns/prod/CICS/smw2int http://winmvs2c.hursley.ibm.com:27728/CICSSystemManagement/schema/CICSSystemManagement.xsd
  version:            3.0
  connect_version:    0610
  resultsummary:
    api_source:        CICSPlex SM
    api_function:      GET
    api_response1:     1027
    api_response2:     0
    api_response1_alt: NODATA
    api_response2_alt:
    recordcount:       0

The only bundle that would return any info is the existing one in this case.

Eg

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics get resource CICSNodejsapp --region-name CALMAS1 --criteria "BUNDLE=CICSJSON" --cics-plex CAPLEX
_keydata:     C3C9C3E2D1E2D6D5404040404040404040404040404040404040404040404040
basdefinever: 0
bundle:       CICSJSON
changeagent:  DREPAPI
changeagrel:  0730
changetime:   2019-06-03T15:34:14.000000+00:00
changeusrid:
cputotal:     634
definesource: CICSJSON
definetime:   2019-06-03T15:34:14.000000+00:00
enablestatus: ENABLED
eyu_cicsname: CALMAS1
eyu_cicsrel:  E730
eyu_reserved: 0
heapappd:     13401056
heapcur:      21004288
heapmax:      1501560832
heaprunt:     4063232
installagent: BUNDLE
installtime:  2019-06-03T15:34:15.000000+00:00
installusrid:
invkcomp:     0
invkcur:      0
invkerr:      0
invkpeak:     0
lerunopts:    DFHSJNRO
log:          /u/atkinc/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190603.T143415.log
name:         CICSJSON
nodehome:     /usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x
pid:          66186
profile:      /u/atkinc/pushtest/CICSJSON_1.0.0/cicsjson.profile
startscript:  /u/atkinc/pushtest/CICSJSON_1.0.0/cicsjson.js
stderr:       /u/atkinc/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190603.T143415.stderr
stdout:       /u/atkinc/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190603.T143415.stdout
trace:        /u/atkinc/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190603.T143415.trace

So the hint is not overly helpful in this case.

**Comment by ChrisAtkinson1** [comment]
It can be misleading in any place where the bundle is not installed.

**Comment by matthewpwilson** [comment]
I think it would be worth at least suppressing the attempt to look at bundle parts and not even fallback to suggesting a command in cases where the bundle doesn't even install.
Finding the old bundle seems like a bit of edge case and lower priority IMO.

**Comment by pcoop** [comment]
The difficulty here is in detecting the different severity of errors. In most failure scenarios the Bundle will have partially deployed and so the diagnostic information is indeed required. In this example you've found a failure where it didn't deploy at all. The question is how to detect that. We could special case the presence of DFHRL2105E as implying that the deploy utterly failed... but are there any other messages that imply the same extreme degree of failure?

Cics-deploy itself ended gracefully in this scenario; it issued the expected diagnostics to report exactly what the problem was. The user then decided to go on and run the optional extra command to query the installed NODEJSAPPs, and yes, that failed; but we didn't tell them they had to do that, just offered it as a suggestion of something they could do.

**Comment by matthewpwilson** [comment]
Can we look for a combination of messages that indicates the bundle didn't install at all? E.g. RL2055 and the absence of the message giving the regions and bundle part statusses?

**Comment by matthewpwilson** [comment]
@ChrisAtkinson1 can you confirm if you're happy with the new error message I added please

**Comment by ChrisAtkinson1** [comment]
New message is fine for me

$ zowe cics-deploy push bundle --name CICSJSO2  --ow
15:04:20.642882 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/06/20 3:04pm
15:04:20.644153 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
15:04:20.646087 :  *
15:04:20.646101 :  SET CICSPLEX(CAPLEX);
15:04:22.680163 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
15:04:24.708857 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
15:04:24.765855 :
15:04:24.765886 :  *
15:04:24.765893 :  DEPLOY BUNDLE(CICSJSO2)
15:04:24.765897 :         BUNDLEDIR(/u/atkinc/pushtest/CICSJSON_1.0.0)
15:04:24.765902 :         SCOPE(CALMAS1)
15:04:24.765906 :         STATE(ENABLED)
15:04:32.868278 :  DFHRL2105E BUNDLE(CICSJSO2) cannot be deployed to SCOPE(CALMAS1) as the bundle ID(CICSJSON                                                        ) is already used by installed BUNDLE(CICSJSON).
15:04:32.868428 :  DFHRL2055I Errors have occurred, processing terminated.
15:04:32.874277 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

An attempt to query the remote CICSplex using the cics plug-in has failed.
DFHDPLOY output implied the bundle failed to install. Check the output above for further information. Consider examining the JESMSGLG, MSGUSR, SYSPRINT and SYSOUT spool files of the CICS region job, or consult your CICS system programmer.
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = DFHDPLOY stopped processing for jobid JOB81647 due to an error.
