### ISSUE TITLE
Add diagram in profile topic

### ISSUE THREAD

**Issue by tasha-m-k** [IBM/zowe-cli-cics-deploy-plugin#232]

**Comment by markcocker** [comment]
I experimented with a diagram vs a table. A table won out for me as the text can link to the named profile further down the page. See PR #278.

**Comment by markcocker** [comment]
Verified:
- new table to replace ToC at start of topic "Creating Zowe CLI profiles" - see https://markcocker.github.io/zowe-cli-cics-deploy-plugin/cdp-Creating-Zowe-CLI-profiles.html#cics-profile
