### ISSUE TITLE
With SSL (or anyother security on) - CMCI query has not error output if user etc is wrong.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#234]
With SSL (or anyother security on) - CMCI query has not error output if user etc is wrong.

It finished like this - (verbose on)

Deploy complete
Gathering scope information
Querying regions in scope over CMCI
PUSH operation completed

Should we report the error ?

**Comment by pcoop** [comment]
This is the same issue as #219, the cics-plugin doesn't offer particularly helpful error messages when something goes wrong. I can dump what it produces to screen if you want, but it's as likely to be actively unhelpful as helpful. See #219 for examples.
