### ISSUE TITLE
verbose and rfj output - is this really easier for scripting ??

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#235]
The output is kinda nuts!

[rfjverbose.txt](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3257987/rfjverbose.txt)

**Comment by ChrisAtkinson1** [comment]
Non verbose I think is fine.

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics-deploy push bundle --name CICSJSON --targetdir /u/atkinc/pushtest --ow  --rfj
{
  "success": true,
  "exitCode": 0,
  "message": "",
  "stdout": "Regions in scope 'CALMAS1' of CICSplex 'CAPLEX':\n   Applid: CALMAS1    jobname: CALMAS1    jobid: JOB94225\n\nNODEJSAPP resources for bundle 'CICSJSON' in scope 'CALMAS1':\nNODEJSAPP resource 'CICSJSON' is in 'ENABLED' state in region 'CALMAS1' with process id '67298'.\n  stdout: /u/atkinc/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190605.T160150.stdout\n  stderr: /u/atkinc/nodelogs/CALMAS1/CICSJSON/CICSJSON/D20190605.T160150.stderr\nPUSH operation completed\n",
  "stderr": "",
  "data": {}
}

**Comment by markcocker** [comment]
If we wanted the --rfj to be useful for scripting (eg. to get the paths to stdout and stderr), I think we would need to create structured information to be contained in the `data` portion of the json, however for the moment I think this is beyond the scope of the use cases we're looking to address.
