### ISSUE TITLE
Specifying the --zosmf stuff on the command line with a bad default profile gives error

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#252]
I altered my default zosmf profile to use bad values.  Then put the good ones on the command line, the pust command failed for some reason.

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\Cicsjson\CICSJSON>zowe cics-deploy push bundle --name CICSJSON --targetdir /u/atkinc/pushtest  --cics-deploy-profile deploy  --ow --v  --zosmf-host  winmvs2c.hursley.ibm.com --zosmf-port 27728  --zosmf-user ATKINC --zosmf-password ****   --zosmf-reject-unauthorized false
WARNING: --cics-host value 'winmvs2x.hursley.ibm.com' does not match --zosmf-host value 'winmvs2c.hursley.ibm.com'.
WARNING: --cics-user value 'atkinac' does not match --zosmf-user value 'ATKINC'.
Making remote bundle directory '/u/atkinc/pushtest/CICSJSON_1.0.0'
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to create directory '/u/atkinc/pushtest/CICSJSON_1.0.0'. Problem is: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The application or context root for this request has not been found: &#047;zosmf&#047;restfiles&#047;fs&#047;u&#037;2Fatkinc&#037;2Fpushtest&#037;2FCICSJSON&#095;1&#046;0&#046;0</p></body></html>

**Comment by ChrisAtkinson1** [comment]
Correction - I did not update the zosmf one - it was the cics profile I managled.  Investigating.

**Comment by ChrisAtkinson1** [comment]
Ok that's me being an idiot user.  With zosmf mangled it works.  However the error output above ( mangled cics profile but good zosmf profile.  Error is due to wrong zosmf port.  Assume the error given is best can do ?

**Comment by ChrisAtkinson1** [comment]
To be clear wrong zosmf port on command line gives the error.

**Comment by pcoop** [comment]
I think a wrong port in the zosmf profile will fail in the same way. It's particularly awkward as something is listening at the port number specified, so rather than failing with a "can't connect" type message it's getting this unpleasant 404.

**Comment by ChrisAtkinson1** [comment]
Yes that's my cmci port

**Comment by pcoop** [comment]
I don't think there's much we can do about it. The same kind of error message is issued if you just run:

```
zowe zosmf check status --host winmvs2c.hursley.ibm.com --port 27728
```

**Comment by ChrisAtkinson1** [comment]
closed as working as expected.
