### ISSUE TITLE
Clarify message when uploading files

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#257]
The progress bar message when uploading eg. `Uploading ...50.png` coould be a bit confusing as files can start with `.`
![image](https://user-images.githubusercontent.com/15351000/59358401-67b89580-8d24-11e9-87d9-be50d61bd53d.png)
Suggest `Uploading file 50.png`

**Comment by matthewpwilson** [comment]
We hook directly into the progress bar provided by the API behind `zowe files upload dir-to-uss` so suggest raising the issue against Zowe CLI.

**Comment by markcocker** [comment]
ok, I found
`options.task.statusMessage = "Uploading ..." + abbreviatedFile;`
in file
https://github.com/zowe/zowe-cli/blob/ffd0350fca8aca3f458dcd52784a086d583354f1/packages/zosfiles/src/api/methods/upload/Upload.ts
Will raise an issue there.

**Comment by pcoop** [comment]
I'm not convinced this is worth reporting. I can't believe anyone will get confused by an ellipsis, it's a fairly common mechanism to indicate truncation. If the progress bar is watched for more than a second its purpose should be obvious.

**Comment by markcocker** [comment]
Ellipsis at the end of a sentence yes, but in the middle with no space after? See https://grammarist.com/usage/eclipses-vs-ellipsis/ 'Most agree that a space before … and after the dots is appropriate.'

**Comment by markcocker** [comment]
Raised https://github.com/zowe/zowe-cli/issues/451
