### ISSUE TITLE
DFHRL2069W from DFHDPLOY on deploy bundle. Should we support both ENABLED/AVAILABLE as target states?

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#26]
When I perform a `deploy bundle` command, I get the following warning from DFHDPLOY:

```
DFHRL2069W BUNDLE(NODETEST) cannot be set to AVAILABLE as it contains no entry points.
```
I think we should set the target state to ENABLED rather than AVAILABLE to avoid this. 

The deploy still succeeds, it's just that the warning might be confusing to the user.

**Comment by pcoop** [comment]
Another option might be to suggest a change to DFHDPLOY. It's not great that our bundle deploying code should have to know about the contents of a Bundle in order to decide whether to aim for AVAILABLE or ENABLED state... maybe DFHDPLOY could downgrade that message to being Informational?

**Comment by matthewpwilson** [comment]
Yes that sounds like a better plan.

**Comment by markcocker** [comment]
Having a warning coming back to the user of the CLI means they'll need to understand what this means and to ignore it. AVAILABLE state is not applicable for CICS bundles containing just Node.js or Java applications. Perhaps we need to default the CLI to ENABLED and allow an override to either DISABLED or AVAILABLE?

Re "maybe DFHDPLOY could downgrade that message to being Informational?" - DFHDPLOY returns RC=4 in this situation that is defined as a warning, and differentiated from RC>=8 that is defined as an error.

**Comment by matthewpwilson** [comment]
Design meeting notes:
Default target state to ENABLED, provide parameter to override.

**Comment by matthewpwilson** [comment]
Working nicely.
