### ISSUE TITLE
Add code of conduct to project

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#261]
Choices:
1. [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct)
   * The [Eclipse Foundation - Community Code of Conduct](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php) is based on V1.1.0 of this.
2. [The Linux Foundation Code of Conduct](https://www.linuxfoundation.org/event/open-networking-summit-2017/code-of-conduct/)
   * [Zowe Charter](https://zowe.org/Zowe-Charter.pdf) is based on this.

General advice about codes of conduct:
* Open Source Guides [Your Code of Conduct](https://opensource.guide/code-of-conduct/#establishing-a-code-of-conduct)

**Comment by matthewpwilson** [comment]
@markcocker could you identify a suitable code of conduct to base ours on please

**Comment by matthewpwilson** [comment]
@markcocker could you identify a suitable code of conduct to base ours on please

**Comment by matthewpwilson** [comment]
@markcocker could you identify a suitable code of conduct to base ours on please

**Comment by tasha-m-k** [comment]
Here's a bunch of IBM Github repos that have a code of conduct: https://www.google.com/search?biw=1680&bih=889&ei=Ko0MXeh1wqKBBrP5pNAI&q=code+of+conduct+site%3Agithub.com%2Fibm&oq=code+of+conduct+site%3Agithub.com%2Fibm&gs_l=psy-ab.3...5443.22854..24577...4.0..0.88.2006.39......0....1..gws-wiz.......0i71j35i39j0i67j0i131j0j0i131i67j0i10i67j0i20i263j0i22i30.3nrVUQYFMpc

They all seem a bit different other that this one that has been used more than once:https://github.com/IBM/kui/blob/master/docs/CODE_OF_CONDUCT.md 
https://github.com/IBM/java-sdk-core/blob/master/CODE_OF_CONDUCT.md
