### ISSUE TITLE
Requierements

### ISSUE THREAD

**Issue by tasha-m-k** [IBM/zowe-cli-cics-deploy-plugin#264]
CICSPlex System Manager (CPSM) is provided with CICS and is required to run the DFHDPLOY utility, and for the zowe cics-deploy push bundle to query application resources "VIA CMCI". CPSM should be connected to the CICS regions into which the application is being installed.

**Comment by markcocker** [comment]
Verified the sentence now reads "CICSPlex System Manager (CPSM) is provided with CICS and is required to run the DFHDPLOY utility, and for the zowe cics-deploy push bundle command to query application resources **via the CICS Management Client Interface (CMCI).**"
