### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by tasha-m-k** [IBM/zowe-cli-cics-deploy-plugin#265]
Summary
To install the Zowe CLI and cics-deploy plug-in, perform the following steps on your local workstation.

**Comment by tasha-m-k** [comment]
Under 5 show the output

**Comment by markcocker** [comment]
Output is:
```
Installed plugins: 

 -- pluginName: zowe-cli-cics-deploy-plugin 
 -- package: zowe-cli-cics-deploy-plugin 
 -- version: 0.5.0 
 -- registry: https://eu.artifactory.swg-devops.com/artifactory/api/npm/cicsts-npm-virtual

-- pluginName: @zowe/cics 
 -- package: @zowe/cics 
 -- version: 2.0.1 
 -- registry: https://eu.artifactory.swg-devops.com/artifactory/api/npm/cicsts-npm-virtual
```

**Comment by ChrisPark89** [comment]
in zowe-cli-cics-plugin, they verify the plugin by doing this:

`$ zowe plugins validate @zowe/cics`
```When you install the plug-in successfully, the following message displays:```
```
Validation results for plugin 'cics':
Successfully validated.
```

Maybe we can do something similar e.g.
`$ zowe plugins validate zowe-cli-cics-deploy-plugin`

**Comment by markcocker** [comment]
> Maybe we can do something similar e.g.
> `$ zowe plugins validate zowe-cli-cics-deploy-plugin`

At the moment on my system this results in the following warnings which aren't helpful to include in the doc:
```
zowe plugins validate zowe-cli-cics-deploy-plugin

_____ Validation results for plugin 'zowe-cli-cics-deploy-plugin' _____

*** Warning: The property '@zowe/cli' does not exist within the 'peerDependencies' property in the file '/Users/cockerma/.zowe/plugins/installed/lib/node_modules/zowe-cli-cics-deploy-plugin/package.json'.

*** Warning: The property '@zowe/imperative' does not exist within the 'peerDependencies' property in the file '/Users/cockerma/.zowe/plugins/installed/lib/node_modules/zowe-cli-cics-deploy-plugin/package.json'.

This plugin has warnings, but its commands and framework overrides will still be available.
```

**Comment by ChrisPark89** [comment]
It's because we recently changed our dependencies to @brightside/*
It solves the problem, if we add @zowe/cli and @zowe/imperative in the peerDependencies in package.json file. I will update the code.

It should print out following:

``` 
jeonghyukpark@jeonghyuks-mbp:~/Documents/dev/cics/zowe-cli-cics-deploy-plugin$ zowe plugins validate zowe-cli-cics-deploy-plugin

_____ Validation results for plugin 'zowe-cli-cics-deploy-plugin' _____
This plugin was successfully validated. Enjoy the plugin.

**Comment by matthewpwilson** [comment]
I don't think we should need peerDependencies for @zowe if we're using lts-incremental. Were you testing this with the lts-incremental version of Zowe CLI? I didn't these mesages.

**Comment by markcocker** [comment]
> Were you testing this with the lts-incremental version of Zowe CLI?

No. When I switched to this version it works fine thanks:
```
$ zowe plugins list

Installed plugins: 

 -- pluginName: @brightside/cics 
 -- package: @brightside/cics@lts-incremental 
 -- version: 1.1.1 
 -- registry: https://registry.npmjs.org/

-- pluginName: zowe-cli-cics-deploy-plugin 
 -- package: zowe-cli-cics-deploy-plugin 
 -- version: 0.5.0 
 -- registry: https://registry.npmjs.org/


$ zowe plugins validate

_____ Validation results for plugin '@brightside/cics' _____
This plugin was successfully validated. Enjoy the plugin.

_____ Validation results for plugin 'zowe-cli-cics-deploy-plugin' _____
This plugin was successfully validated. Enjoy the plugin.
```

**Comment by markcocker** [comment]
> Maybe we can do something similar e.g.

I suggest the `Installing` documentation topic **does not** suggest running `zowe plugins validate` as this is automatically run as part of  step 4 `zowe plugins install`
