### ISSUE TITLE
Creating profiles

### ISSUE THREAD

**Issue by tasha-m-k** [IBM/zowe-cli-cics-deploy-plugin#267]
Beware: in Zowe profiles passwords are stored in plain text.

**Comment by tasha-m-k** [comment]
Last command on page : zowe cics get resource CICSRegion - needs region name and show expected output

**Comment by tasha-m-k** [comment]
SSH profile: add to create an SSH profile with certificate
Link out to documentation. Chris A to send info.

**Comment by markcocker** [comment]
> Last command on page : zowe cics get resource CICSRegion - needs region name and show expected output

PR #278 has added region-name to the cics zowe plug-in profile, so you do not need to specify the region name. It also adds example output.

**Comment by ChrisAtkinson1** [comment]
You should be able to add an ssh key like this.

ssh-keygen  -> follow prompts

ssh-copy-id -i yourkeyfile  pub user@host

Some info from the internet.
https://www.ssh.com/ssh/keygen/

I did it a while back on windows - but currently I can no longer get it to work

**Comment by matthewpwilson** [comment]
Mark to add a note in doc to say passwords in profiles may be stored in plain text
