### ISSUE TITLE
Should deploy bundle perform an undeploy beforehand? Do we need an --overwrite option?

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#27]
The current behaviour of `zowe cics-deploy deploy bundle` is that it tells DFHDPLOY to do an UNDEPLOY BUNDLE followed by a DEPLOY BUNDLE.

As this is one of our 'atomic commands', I'm wondering if it would be better to to just do the DEPLOY.  It's then up to the user to script an `undeploy bundle` followed by a `deploy bundle` if they want to do that.

A use-case where you might not want to UNDEPLOY first is a first-time deployment you're not sure if you've got a unique BUNDLE resource name.  You're expecting the DEPLOY to just work, but if you picked a name that was already used you will inadvertently undeploy someone else's application. 

An alternative would be to provide a command line argument to perform the UNDEPLOY first (maybe `--force`?)

I'd expect our `cics-deploy push` command to combine the undeploy and the deploy.

**Comment by matthewpwilson** [comment]
@pcoop @markcocker thoughts?

**Comment by pcoop** [comment]
FWIW, I implemented it with an auto-undeploy as that's what the sample JCL for DFHDPLOY in the KC suggested. The zowe profiles command uses an --overwrite toggle for folks to use to indicate whether they want to replace an existing profile option or not, we could implement that for deploy bundle.

We might want to have a similar conversation about whether to update an existing manifest during bundle generation, or overwrite existing files during upload.

**Comment by markcocker** [comment]
Changing `zowe cics-deploy deploy bundle` to only perform a deploy would make it run faster. It should be easy enough to script `zowe cics-deploy undeploy bundle` before it if that is what is needed. Also failures in one or the other command will be more obvious (ie. if deploy bundle failed, was it because it did not undeploy or did not deploy).

**Comment by matthewpwilson** [comment]
Design meeting notes:
Don't undeploy at all as part of deploy, separate undeploy can be scripted beforehand if needed
For push, the default should be undeploy first.

**Comment by matthewpwilson** [comment]
Confirming the new behaviour's implemented.
