### ISSUE TITLE
Running without profiles - Error on jobcard.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#279]
Command line 
zowe cics-deploy push bundle --n CICSJSON --targetdir /u/atkinc/pushtest --zosmf-host winmvs2c.hursley.ibm.com --zosmf-port 32070 --zosmf-user ATKINC --zosmf-password **** --zosmf-reject-unauthorized false --ssh-password ***  --ssh-host winmvs2c.hursley.ibm.com --ssh-port 22 --ssh-user ATKINC  --ssh-private-key C:\\Users\\CHRISTOPHERAtkinson\\Documents\\ZoweStuff\\ZOWEDEV\\PUSH1\\mykey --ssh-key-passphrase mysshpwd --ssh-handshake-timeout 1000 --cics-host winmvs2c.hursley.ibm.com --cics-port 27728 --cics-user ATKINC --cics-password *** --cics-reject-unauthorized false --cics-protocol https --ow --cicsplex CAPLEX --scope CALMAS1 --csd-group NODELINE  --cics-hlq ANTZ.CICS.TS.DEV.INTEGRAT --cpsm-hlq ANTZ.CICS.TS.DEV.INTEGRAT --description HELLOCMDLINE --job-card "//DFHDPLOY JOB DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT,SYSAFF=MV2C" --timeout 1799 --target-state DISABLED

If I quote the JOBCARD
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = --jobcard parameter does not start with //

If I remove the "" quotes
Syntax Error:
You specified the following unknown values: "JOB", "DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT,SYSAFF=MV2C".

 Could not interpret them as a group, command name, or positional option.

Example:

 - Push a CICS bundle from the working directory by using default cics-deploy,
 cics, ssh and zosmf profiles:

      $ zowe cics-deploy push bundle --name EXAMPLE --target-directory /u/example/bundles

Use "zowe cics-deploy push bundle JOB DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT,SYSAFF=MV2C --help" to view command description, usage, and options.

**Comment by pcoop** [comment]
Zowe allows me to use quotes on the command line with no problems... could this be another git-bash issue?

**Comment by ChrisAtkinson1** [comment]
Yes it appears to be - fails in gitbash.  Works in Node.js windows cmd console and in Windows Powershell

**Comment by pcoop** [comment]
I guess we could add special case code to tolerate quotes with gitbash. The challenge is that quotes could be used around any value (though there's little reason to use them elsewhere).

**Comment by markcocker** [comment]
Do single quotes work?

**Comment by ChrisAtkinson1** [comment]
No single quotes did not work in GitBash

**Comment by pcoop** [comment]
I've added a change to pull request #276 that should tolerate quotes around the job-card if the shell dosn't remove them itself. The problem is nothing to do with running without a profile (it's likely that the same issue with quotes would occur when creating a profile too), it's just the shell being unpredictable.

**Comment by ChrisAtkinson1** [comment]
This does not work.  Either single or double quotes

Command Error:
A failure occurred during CICS bundle pushing.
 Reason = --jobcard parameter does not start with //

[zowe.log](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3310692/zowe.log)

**Comment by pcoop** [comment]
The log file is useful, it shows the problem. The job-card parameter has the value:

/DFHDPLOY JOB DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT,SYSAFF=MV2C

That is, there's a single leading slash where a double slash should be. Assuming a double slash was entered at the comment line (something I can't verify from the log) then gitbash has removed one of them... the change I made to tolerate the presence of quotes might have been irrelevant.

**Comment by ChrisAtkinson1** [comment]
There was a double slash.

**Comment by matthewpwilson** [comment]
So using four slashes on the command line might be the answer?

**Comment by ChrisAtkinson1** [comment]
It appears not 

$ zowe cics-deploy push bundle --n CICSJSON --targetdir /u/atkinc/pushtest --zosmf-host winmvs2c.hursley.ibm.com --zosm
f-port 32070 --zosmf-user ATKINC --zosmf-password * --zosmf-reject-unauthorized false --ssh-password   * -
-ssh-host winmvs2c.hursley.ibm.com --ssh-port 22 --ssh-user ATKINC   --cics-host winmvs2c.hursley.ibm.com --cics-port 2
7728 --cics-user ATKINC --cics-password * --cics-reject-unauthorized false --cics-protocol https --ow --cicsplex
 CAPLEX --scope CALMAS1 --csd-group NODELINE  --cics-hlq ANTZ.CICS.TS.DEV.INTEGRAT --cpsm-hlq ANTZ.CICS.TS.DEV.INTEGRAT
 --description HELLOCMDLINE --job-card "////DFHDPLOY JOB DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT,SYSAFF=MV2C" --timeou
t 1799 --target-state DISABLED
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = --jobcard parameter does not start with a suitable jobname: '///DFHDPLOY '

[zowe.log](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3311319/zowe.log)

**Comment by matthewpwilson** [comment]
Paul put a further fix in to tolerate a single slash so hopefully this should work now?

**Comment by ChrisAtkinson1** [comment]
The fix works in gitbash and normal shell and powershell

Double quotes and //JCCARD in both.  Single quotes do not work.  Assume this is fine ?

**Comment by matthewpwilson** [comment]
Agreed single quotes not required
