### ISSUE TITLE
Error message from deploy bundle with an overlength jobcard is not nice

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#30]
```
zowe cics-deploy deploy bundle --name FREYJA --bundledir /u/wilson/freyjademo --jobcard "//MWDEPLOY JOB a very long jobcard which is an exceeding bad thing to do because it will break"
Command Error:
A failure occurred during CICS bundle deployment.
 Reason = Failure occurred submitting DFHDPLOY JCL: 'z/OSMF REST API Error:
Rest API failure with HTTP(S) status 400
message:  Job submission error. Record length 94 too long for JCL submission, maxlen=80
category: 6
reason:   9
rc:       4
```
Suggest it would be worth checking the length of the jobcard parameter ourselves

**Comment by pcoop** [comment]
I presume the suggestion here is that we could attempt to auto-wrap the jobcard if it's too long. The current error message is what comes from submitJobs, I don't think we can change that, but we could try to avoid the problem in our code.

I had kinda hoped that submitJobs would be smart enough to implement some auto-wrapping of its own... clearly that isn't the case. I suppose we could contemplate implementing that enhancement ourselves.

**Comment by matthewpwilson** [comment]
I think it would sufficient just to validate the length of the supplied jobcard and complain if too long. The error message could just splitting it manually.

**Comment by matthewpwilson** [comment]
This is great improvement. I've found an edge case where it maybe does not quite as intended: the value of the parameter  MSGLEVEL can include commas e.g `MSGLEVEL=(2,1)`
However this still produces valid JCL so I think we're OK.
