### ISSUE TITLE
NLS Enable messages

### ISSUE THREAD

**Issue by pcoop** [IBM/zowe-cli-cics-deploy-plugin#31]
Should we consider allocating DFHRLxxxx message numbers for each message issued? Something from a range adjacent to that of DFHDPLOY; it'll allow us to provide a more detailed user-response for each such message. We'd document them in the CICS KC, but they would at least by Googleable.

As part of that work we should extract the text of the messages into a format that can be translated.

**Comment by matthewpwilson** [comment]
TBD awaitng Zowe extenders meeting

**Comment by pcoop** [comment]
There are two parts to this, externalising the text of the messages (so that they can in theory be translated), and giving the messages unique identifiers that can be documented. I've looked around in zowe-cli for an existing convention here, as far as I can tell there is no attempt at Internationalisation/Globalisation of the code. If we decide to do this we might have to invent our own solution (or use an existing 3rd party library for this type of thing).

If we were working on a traditional product offering then we'd be required to NLS enable the code... but as this is an open source plugin I guess the expectation is different.

**Comment by markcocker** [comment]
NLS support for Zowe CLI plugins has been raised as issue https://github.com/zowe/vscode-extension-for-zowe/issues/90
