### ISSUE TITLE
How does the user know where stdout/stderr are?

### ISSUE THREAD

**Issue by pcoop** [IBM/zowe-cli-cics-deploy-plugin#33]
Suppose a Node.js Bundle is deployed successfully to CICS without error, that's awesome! Now what? As the user, how do I know where my stderr/stdout output gets written by CICS? Or suppose something goes wrong, how do I find the error messages issued to stderr, SYSPRINT, MSGUSR, JESMSGLG?

Maybe we need an extra activity that can be scripted after the DEPLOY (or perhaps as part of DEPLOY) that uses CMCI to query aspects of (one of) the region(s) that the Bundle was deployed to. It'd be good to provide the user with a zowe command they could issue to view the JESMSGLG, etc. (perhaps starting at a particular timestamp within the logs), and to view the output files on zFS.

If we require CMCI in order to do this then that will be a 4th profile to configure, the first three being zosMF, SSH and cics-deploy.

**Comment by markcocker** [comment]
It would be nice to return for each NODEJSAPP in the bundle the fully qualified/resolved name of STDOUT/STDERR/TRACE. The user could then use other zowe commands or cut&paste into an FTP client to get the relevant files. However, this could be somewhat overly complex if the bundle is deployed to multiple CICS regions.

**Comment by matthewpwilson** [comment]
Create a cics-deploy inquire which will give stdout, stderr locations / commands to get them, and message log with timestamp range
Probably do this as part of push of deploy fails

**Comment by ChrisAtkinson1** [comment]
I am creating a box note - of errors 

Some ok from dfhploy and some maybe need some enhancements.

https://ibm.ent.box.com/notes/438003556917
