### ISSUE TITLE
Do we need async access to DFHDPLOY messages?

### ISSUE THREAD

**Issue by pcoop** [IBM/zowe-cli-cics-deploy-plugin#35]
The DEPLOY/UNDEPLOY actions can take a while to run, DEPLOY regularly takes about 30 seconds for me. Watching a static screen while waiting for it to complete isn't great. I've implemented a progress bar, and maybe that's sufficient, but should we be looking for something better? We could (attempt) to poll the JES output and display in an approximation of real-time. 

Is it worth the effort to do that? It wont make things run any faster, but might be less tedious.

**Comment by markcocker** [comment]
This sounds like a general requirement for job submission via z/OSMF.

**Comment by matthewpwilson** [comment]
Design meeting notes:
This is lower priority, not worth us spending a lot of effort on ourselves.
