### ISSUE TITLE
What should go in the generated Node.js profile?

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#36]
The generate bundle command currently generates a Node.js profile with an include statement. This means it won't work by itself, someone needs to create that include file or edit the generated profile. The name of the include file we generate contains the name of the NODEJSAPP, so you'd need to create a unique file for each app following this scheme.

Other options include:
- Generate a profile with no includes.  This might work out of the box if the defaults are suitable. This could be the template profile we ship with CICS including all the comments.
- Generate a profile with a 'static' include. This patterns suggests that you put everything system-related like WORK_DIR and NODE_HOME in a single include file that could be included by all apps.  You'd still need to set PORT in the app profile.

Here's the complete profile we're currently generating:
```
# This is a profile for a CICS NODEJSAPP resource

# Import the provisioned configuration file for this NODEJSAPP,
# this file must be created before this Bundle can be installed in CICS
INCLUDE=&USSCONFIG;/nodejsapps/cics-nodejs-invoke.included.profile

# Set the PORT envionment variable, application code should reference this
# value in preference to a hard-coded port number, the value references an
# environment variable that will be configured within the provisioned configuration file.
PORT=&HTTP_PORT;
```

**Comment by markcocker** [comment]
How about
```
# This CICS Node.js application profile is used to configure how CICS controls the
# Node.js runtime, provide Node.js command line options, and to set environment
# variables for use by the application.

# Lines starting with # are treated as comments and ignored.
# Lines ending with \ are continued on the next line.

# See topic "Node.js profile validation and properties" in the CICS Knowledge Center:
# http://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0

# Include a profile that specifies NODE_HOME, WORK_DIR and other configuration 
# that can be shared by several Node.js applications.
INCLUDE=&USSCONFIG;/nodejsapps/general.profile

# Application environment variables 
PORT=&HTTP_PORT;
```

**Comment by pcoop** [comment]
The challenge with the suggested text is that it's unpleasant if you're going to host more than one NODEJSAPP in a given region. They can't all share the same static HTTP_PORT value.

We could set PORT to &NODEJSAPP;_PORT and have it set from a common include, but it doesn't really solve the problem, someone will still have to provision a value before the deployed application will work.

Another option would be to remove PORT from the generated profile entirely unless the user explicitly sets a value. In so doing we'd recognise that we can't provision a port and shouldn't act as though we can.

**Comment by matthewpwilson** [comment]
I think it makes sense to keep the port in the app-specific part of the profile in the bundle rather than in an included file. For unit-testing Freyja might be assigned a port or range of ports by Stan and she can put one in there.  For production that port will likely need to change, but we don't have a neat mechanism to handle that...

**Comment by matthewpwilson** [comment]
Design meeting comments:
Update sample profile (from Explorer) to refer to generic include file
Don't generate PORT= unless --port is specified
