### ISSUE TITLE
Is DEPLOY too verbose in golden path scenarios? Or too techie?

### ISSUE THREAD

**Issue by pcoop** [IBM/zowe-cli-cics-deploy-plugin#40]
DFHDPLOY will generate quite a lot of text that might not mean very much to our Freyja persona, should we hide some of it by default? It's probably needed if something goes wrong, but if everything works we could suppress much of the output.

On a related note, are the messages and other externals too CICS specific? Would it be better for our user not to even know about DFHDPLOY, perhaps we should seek generic terms in which to describe what's happening?

**Comment by matthewpwilson** [comment]
I reckon when the deployment succeeds, a simple message such as "Bundle deployed successfully" should suffice.  However that leaves the question of what to do with warnings, perhaps extract those and display them rather than the complete output?

**Comment by pcoop** [comment]
A simple response in golden path scenarios makes sense to me... but that suggests that we forget about streaming the DFHDPLOY output in real time (issue #34 / Issue #35) as we can't know in a streaming scenario whether it's worked until processing reaches the end.

**Comment by matthewpwilson** [comment]
Perhaps we could provide a `--verbose` which streams the DFHDPLOY output back to the terminal.

**Comment by markcocker** [comment]
> Perhaps we could provide a `--verbose` which streams the DFHDPLOY output back to the terminal.

That would be useful for automation to keep a detail log in one place, even if it is successful.

**Comment by matthewpwilson** [comment]
Design meeting notes:
No DFHDPLOY output if the deploy works, --verbose provides complete output

**Comment by matthewpwilson** [comment]
I can confirm the new behaviour's implemented.
