### ISSUE TITLE
Allow DFHDPLOY to manage the bundle definition

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#41]
We currently require either --resgroup or --csdgroup to be specified. However, the DFHDPLOY doc states that if you don't specify either, it will create the definition in BAS and discard it afterwards. I think we should support this approach, it simplifies things for Freyja.

**Comment by pcoop** [comment]
Yup, fair comment, I'd missed that they could both be legitimately absent.

**Comment by matthewpwilson** [comment]
Fixed
