### ISSUE TITLE
Should --port be renamed for Generate Bundle?

### ISSUE THREAD

**Issue by pcoop** [IBM/zowe-cli-cics-deploy-plugin#45]
We have a CMCI port, a zosMF port, maybe an SSH port... perhaps these things need a little disambiguation when they're all used together? We could rename --port to --nodeport perhaps?

**Comment by pcoop** [comment]
We're not planning to combine 'generate' with 'push' so maybe the ambiguity isn't an issue. But we are considering broadening 'generate' to work with other types of bundles, perhaps the parameters that are specific to Node.js should be renamed now while it's easy to do that. Perhaps to something like:

  --nodejsapp-name
  --nodejsapp-startscript
  --nodejsapp-port

If we add support for Java, or events, or policy, etc. in the future then we could similarly scope their resource specific parameters.

**Comment by markcocker** [comment]
Above sounds a good idea to me.

**Comment by pcoop** [comment]
Matthew and I were chatting about this one yesterday... we're not so sure that we want to make any changes here after all. My original concern over --port has gone, and we like the simplicity of the parameters as they stand.

If we do add support for new adding new resource types in the future, odds are that we couldn't do it automatically using the generate command anyway. Maybe we'd use a new 'add bundle' command, or something like that. Either way, making the externals uglier now for a future use-case that may or may not emerge isn't compelling. We'd retain the option of adding a new alias for the commands in the future if we wanted to do so, we could make --nodejsapp-name an alias for --name at that time.
