### ISSUE TITLE
Build should generate a .md file that summarise the help for all commands

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#58]
It would be useful for the build to create a .md file that includes the same source as the command line help for all of the cics-deploy commands, with an TOC/index at the start and HTML anchors into each command and each option. We could then link into this file from the wiki and other locations as _the_ definitive source of parameter help, and it can be found and indexed by search engines. This would also allow the wiki to focus on use cases, rather than duplicating reference information that could become stale.

I have prototyped what the file could look like in the wiki [Commands.md](https://github.com/IBM/zowe-cli-cics-deploy-plugin/wiki/Commands)

This could use a similar approach to that used by the Zowe CLI that generate [Zowe CLI Help](https://github.com/zowe/zowe-cli/blob/master/docs/CLIReadme.md).

**Comment by matthewpwilson** [comment]
First pass of the generated file is here: https://github.com/IBM/zowe-cli-cics-deploy-plugin/blob/master/docs/CLIReadme.md

BTW @markcocker if this is the kind of 'blob' URL you mentioned I think it's just GitHub's way of linking into the repo

**Comment by markcocker** [comment]
Looks great. A couple of minor improvements:
1. The line under `Usage` would ideally be surrounded by: ```console to help them stand out.
2. The lines starting with Default value eg. `Default value: //DFHDPLOY JOB DFHDPLOY,CLASS=A,MSGCLASS=X,TIME=NOLIMIT` are not aligned with the previous paragraph indentation.
3. The first line under heading `Examples`is not correctly formatted as a markdown bullet.
4. Do we need `$` at the beginning of each example command?
5. In the table of contents, I was expecting generate/push/deploy/undeploy to be under a "cics-deploy" heading. This would match the style in https://github.com/zowe/zowe-cli/blob/master/docs/CLIReadme.md where the TOC level 1 is the command group (config/plugins/profiles...), level 2 is the command.

**Comment by matthewpwilson** [comment]
All our script is doing is calling the Imperative help generator for each command group in our configuration, asking it produce output in Markdown. So unfortunately we have no direct control over the formatting of what it produces for each command.  We could raise an issue and/or PR on Imperative to fix up some of this stuff, the bit about Examples definitely looks like a bug.

**Comment by markcocker** [comment]
For (2) and (3) I have raised https://github.com/zowe/zowe-cli/issues/326

**Comment by markcocker** [comment]
(1) and (4) are requirements on the zowe-cli that are not as important as the above issue I raised so will drop those.

The only issue remaining is (5). If we could group those commands, without adversely changing the command line syntax then great. If not, we can close this.

**Comment by matthewpwilson** [comment]
I've also noticed the 'Usage' line for each of our commands omits the 'cics-deploy' when rendered in the markdown. It appears correctly when the help is generated on the command line.

**Comment by markcocker** [comment]
> I've also noticed the 'Usage' line for each of our commands omits the 'cics-deploy' when rendered in the markdown

I have added that to the above Zowe CLI issue.

**Comment by matthewpwilson** [comment]
I think it's a product of us co-opting their script for running as a plugin... if I generate the help for zowe CLI with our plugin installed, it does it correctly.   This might be a way forward for us... generate as we were generating the help for the whole CLI, and just filter out the bits we don't want.

**Comment by markcocker** [comment]
https://github.com/zowe/zowe-cli/issues/326 has been assigned so waiting to see if it is progressed before closing this issue.

**Comment by markcocker** [comment]
@matthewpwilson @pcoop Changes for zowe/zowe-cli#326 have been merged and https://github.com/zowe/zowe-cli/issues/326#issuecomment-489115271 suggests changes to be made the definition passed to the help generator  .

**Comment by matthewpwilson** [comment]
@markcocker #161 picks up the fixes in Imperative and implements the fix suggested on our end. CLIReadme.md is now looking pretty good :-D

**Comment by markcocker** [comment]
@matthewpwilson Yes looks great now thanks.
