### ISSUE TITLE
Online help shows "bright" instead of "zowe"

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#59]
`zowe cics-deploy undeploy bundle --help` and others displays "bright" or "$ bright" instead of "zowe" command in the usage and examples sections, eg:
```
USAGE
 -----

   bright cics-deploy undeploy bundle [options]
```
and
```
EXAMPLES
 --------

   - Undeploy a CICS bundle using the default cics-deploy
   profile:

      $ bright cics-deploy undeploy bundle --name EXAMPLE
```

**Comment by matthewpwilson** [comment]
That's generated by Zowe CLI and beyond our control. I see 'zowe' in my output though (with Zowe CLI built from source at 3.4.0-alpha.201904021322), so looks like they've fixed this at some point. What version of Zowe CLI do you have?

**Comment by markcocker** [comment]
```
zowe --version
2.1.0
```

**Comment by pcoop** [comment]
FWIW, I'm using zowe 2.12.0 and still see 'bright' in all the externals. Looks like it's version 3 that will resolve that.
