### ISSUE TITLE
Windows - can not use cics-deploy bundle due to invalid bundleDir

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#60]
If I run without escaped directorys on windows - the home directory get U: prefix.

$ zowe cics-deploy deploy bundle --name LOOPER --bundledir /u/atkinc/bundles/Looper_1.0.0/ --cics-deploy-profile allregs --zosmf-p zosmf2c
16:17:51.479313 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/08 4:17pm
16:17:51.480097 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
16:17:51.481305 :  *
16:17:51.481312 :  SET CICSPLEX(CAPLEX);
16:17:53.539701 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
16:17:55.578787 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
16:17:55.593846 :
16:17:55.593856 :  *
16:17:55.593862 :  DEPLOY BUNDLE(LOOPER)
16:17:55.593866 :         BUNDLEDIR(U:/atkinc/bundles/Looper_1.0.0/)
16:17:55.593871 :         SCOPE(ALLREGIN)
16:17:55.593875 :         STATE(ENABLED)
16:17:55.611459 :  DFHRL2020E Unable to read contents of file U:/atkinc/bundles/Looper_1.0.0/META-INF/cics.xml. File could not be found.
16:17:55.611506 :  DFHRL2055I Errors have occurred, processing terminated.
16:17:55.613770 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

If I escape the directories - I get invalid bundleDir

$ zowe cics-deploy deploy bundle --name LOOPER --bundledir //u//atkinc//bundles//Looper_1.0.0// --cics-deploy-profile allregs --zosmf-p zosmf2c
16:20:55.227152 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/08 4:20pm
16:20:55.227838 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
16:20:55.229048 :  *
16:20:55.229055 :  SET CICSPLEX(CAPLEX);
16:20:57.290464 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
16:20:59.339345 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
16:20:59.355429 :
16:20:59.355463 :  *
16:20:59.355504 :  DEPLOY BUNDLE(LOOPER)
16:20:59.355544 :         BUNDLEDIR(//u//atkinc//bundles//Looper_1.0.0//)
16:20:59.355582 :         SCOPE(ALLREGIN)
16:20:59.355622 :         STATE(ENABLED)
16:21:05.514483 :  DFHRL2049I Creating BUNDLE definition.
16:21:05.516579 :  DFHRL2301E BUNDLE(LOOPER) cannot be deployed as the following attributes contain invalid characters: BUNDLEDIR                                                       .
16:21:05.517883 :  DFHRL2055I Errors have occurred, processing terminated.
16:21:05.521436 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\CICS\cics-deploy\zowe-cli-cics-deploy-plugin\lib\cli\deploy\bundle/DeployBundle.handler"
Message:
A failure occurred during CICS bundle deployment.
 Reason = DFHDPLOY stopped processing due to an error.
Stack:
Error: A failure occurred during CICS bundle deployment.
 Reason = DFHDPLOY stopped processing due to an error.
    at DeployBundleHandler.<anonymous> (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\CICS\cics-deploy\zowe-cli-cics-deploy-plugin\lib\cli\shared\BundleParent.handler.js:70:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\CICS\cics-deploy\zowe-cli-cics-deploy-plugin\lib\cli\shared\BundleParent.handler.js:15:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by matthewpwilson** [comment]
We've seen similar symptoms before when using `path.join()` and `path.normalize()` when working with USS paths, as these APIs follow the local operating system's path conventions.  The fix was to use the `path.posix` variants of these APIs. Need to investigate the code to see if we have the same issue here.

**Comment by pcoop** [comment]
FWIW, I can't reproduce this problem on Windows at the moment (though I might have different levels of dependencies installed). I can't find anywhere in the code that we even manipulate that value, it just gets inserted into the generated JCL as supplied by the caller, so I wouldn't expect it to need escaping.

I suppose Imperative might be pre-processing the value in some way before it reaches our code, I could add validation to reject paths that don't appear valid up front (before we submit the JCL), but that wont help much other than to reduce the window in which the problem is being injected. It might be worth checking the version of Zowe that's being used; I updated to a build of 3.4.0 yesterday (but I didn't experience the problem back when I was at 2.12.0 either).

**Comment by ChrisAtkinson1** [comment]
I have - $ zowe -V
2.15.0

**Comment by ChrisAtkinson1** [comment]
This is still the problem with zowe 3.3.  If I don't quote escape the path - it puts in the U: on my userid.
I have seen this before - and the way round it on my Windows system was to escape.  Doing this sees the path passed to DFHDPLY as escaped which it regects as above.  This is the latest output from the plugin and zowe 3.3.

$ zowe cics-deploy deploy bundle --name LOOPER --bundledir /u/atkinc/bundles/Looper_1.0.0/ --cics-deploy-profile allreg
s --zosmf-p zosmf2c
17:07:07.035123 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/09 5:07pm
17:07:07.035840 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
17:07:07.037166 :  *
17:07:07.037173 :  SET CICSPLEX(CAPLEX);
17:07:09.091588 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
17:07:11.132334 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
17:07:11.149102 :
17:07:11.149113 :  *
17:07:11.149119 :  DEPLOY BUNDLE(LOOPER)
17:07:11.149123 :         BUNDLEDIR(U:/atkinc/bundles/Looper_1.0.0/)
17:07:11.149127 :         SCOPE(ALLREGIN)
17:07:11.149131 :         STATE(ENABLED)
17:07:11.171135 :  DFHRL2020E Unable to read contents of file U:/atkinc/bundles/Looper_1.0.0/META-INF/cics.xml. File could not be found.
17:07:11.171188 :  DFHRL2055I Errors have occurred, processing terminated.
17:07:11.173686 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Command Error:
A failure occurred during CICS bundle deployment.
 Reason = DFHDPLOY stopped processing due to an error.


AzureAD+CHRISTOPHERAtkinson@LAPTOP-0JDQI4PC  ~/Documents/ZoweStuff/ZOWEDEV/CICS/tests
$ zowe -V
3.3.0

**Comment by matthewpwilson** [comment]
Can you try putting the USS path in quotes please. If still an issue then please can you attach your Zowe log file (.zowe/zowe/logs/zowe.log inside your home directory)

**Comment by ChrisAtkinson1** [comment]
Still and error eg

AzureAD+CHRISTOPHERAtkinson@LAPTOP-0JDQI4PC  ~/Documents/ZoweStuff/ZOWEDEV/CICS/tests
$ zowe cics-deploy deploy bundle --name LOOPER --bundledir "/u/atkinc/bundles/Looper_1.0.0/" --cics-deploy-profile allr
egs --zosmf-p zosmf2c
11:23:44.149352 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/10 11:23am
11:23:44.150384 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
11:23:44.151591 :  *
11:23:44.151598 :  SET CICSPLEX(CAPLEX);
11:23:46.214814 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
11:23:48.261513 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
11:23:48.278373 :
11:23:48.278386 :  *
11:23:48.278392 :  DEPLOY BUNDLE(LOOPER)
11:23:48.278397 :         BUNDLEDIR(U:/atkinc/bundles/Looper_1.0.0/)
11:23:48.278401 :         SCOPE(ALLREGIN)
11:23:48.278405 :         STATE(ENABLED)
11:23:48.312462 :  DFHRL2020E Unable to read contents of file U:/atkinc/bundles/Looper_1.0.0/META-INF/cics.xml. File could not be found.
11:23:48.312516 :  DFHRL2055I Errors have occurred, processing terminated.
11:23:48.314772 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).
[zowe.log](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3063280/zowe.log)

Command Error:
A failure occurred during CICS bundle deployment.
 Reason = DFHDPLOY stopped processing due to an error.

**Comment by matthewpwilson** [comment]
The path already has the U: in it by the time it gets to our handler. So our code is not the culprit. But what is?

**Comment by matthewpwilson** [comment]
Are you running zowe-cli from gitbash?  If so I think it could be trying to be clever and munging the path:
https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line
The fix should be to add just a single extra / at the beginning of the path, which the shell should should strip off.

**Comment by ChrisAtkinson1** [comment]
No joy with that.

$ zowe cics-deploy deploy bundle --name LOOPER --bundledir //u/atkinc/bundles/Looper_1.0.0/ --cics-deploy-profile allre
gs --zosmf-p zosmf2c
11:51:31.677285 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/10 11:51am
11:51:31.678321 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
11:51:31.679847 :  *
11:51:31.679856 :  SET CICSPLEX(CAPLEX);
11:51:33.768287 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
11:51:35.806777 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
11:51:35.823696 :
11:51:35.823706 :  *
11:51:35.823712 :  DEPLOY BUNDLE(LOOPER)
11:51:35.823717 :         BUNDLEDIR(//u/atkinc/bundles/Looper_1.0.0/)
11:51:35.823721 :         SCOPE(ALLREGIN)
11:51:35.823725 :         STATE(ENABLED)
11:51:42.031133 :  DFHRL2049I Creating BUNDLE definition.
11:51:42.032798 :  DFHRL2301E BUNDLE(LOOPER) cannot be deployed as the following attributes contain invalid characters: BUNDLEDIR                                                       .
11:51:42.034379 :  DFHRL2055I Errors have occurred, processing terminated.
11:51:42.038471 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

**Comment by matthewpwilson** [comment]
So now we know it's GitBash that's munging the path, I think you'll just need to find out the right way to tell it not to!  Perhaps you can turn off this path munging behaviour completely? I think we just happened to 'get away' with the extra slashes elsewhere, but DFHDPLOY doesn't tolerate them.

**Comment by ChrisAtkinson1** [comment]
I tried looking and changing this before following the stackoverflow links and it just does NOT turn off!

**Comment by ChrisAtkinson1** [comment]
Can our code be a little cleverer with the path ?  Strip out any // ?

**Comment by matthewpwilson** [comment]
Yeah I'll do that

**Comment by matthewpwilson** [comment]
@ChrisAtkinson1 this should be working now with the latest build.
