### ISSUE TITLE
We should allow the user to specify the LPAR DFHDPLOY runs on

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#62]
It would be good if we could allow a SYSPARM to allow DFHDPLY to run on a different LPAR than the zOS/MF is running on.

**Comment by matthewpwilson** [comment]
I think you should be able to do this by specifying SYSAFF as part of the jobcard in the profile.

**Comment by markcocker** [comment]
@ChrisAtkinson1 Are you ok for this be be closed?

**Comment by ChrisAtkinson1** [comment]
Yes works with SYSAFF - with profiles running on same system.  (SYSAFF to another)
