### ISSUE TITLE
Unhelpful error message if bundle is uploaded without .zosattributes ( or ones that would be invalid)

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#74]
11:26:52.448922 :  DFHRL2131I Waiting for BUNDLE(CICSPH02) to be installed in active regions in SCOPE(CALMAS1).
**11:26:54.461144 :  **DFHRL2300E BUNDLE(CICSPH02) cannot be deployed. The reason for the failure could not be determined.****
11:26:54.467623 :  DFHRL2055I Errors have occurred, processing terminated.
11:26:54.472497 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Command Error:
A failure occurred during CICS bundle pushing.
 Reason = DFHDPLOY stopped processing due to an error.

Actual cause of this error - ( I just copied on from explorer and it did not have a .zosattribute files with it)

DFHRL0107 I 04/17/2019 11:26:52 CALMAS1 CICSUSER The CICS resource lifecycle manager has started to create the BUNDLE resource     
           CICSPH02.                                                                                                               
**DFHRL0112 E 04/17/2019 11:26:52 CALMAS1 COIE The encoding of the manifest /u/atkinc/pushtest/CICSPH02/META-INF/cics.xml in the root**
           directory of the bundle CICSPH02 is not valid.                                                                          
DFHRL0110 E 04/17/2019 11:26:52 CALMAS1 COIE The CICS resource lifecycle manager has failed to create the BUNDLE resource CICSPH02.

**Comment by pcoop** [comment]
Bundle push is unlikely to work without a .zosattributes file, so I suppose we could either reject a Bundle that doesn't include one, or apply a default set of attributes if there's none in the Bundle.

My experience was that the file upload process had a tendency to fail (with arguably even less useful error messages than seen here) if .zosattributes is missing, I'm a little intrigued that you're getting as far as experiencing a DFHDPLOY failure. I'm sure we can do better, just unsure as to whether a hard failure would be the best option or not.

**Comment by matthewpwilson** [comment]
:+1: for applying a default .zosattributes if none is provided, I suggest giving a warning message in this situation.

**Comment by ChrisAtkinson1** [comment]
Warning given.
