### ISSUE TITLE
Generate of bundle ignores a profile in my directory.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#75]
When I generate a bundle - it creates a sub directory with the nodejsapp bundle part, and a profile ( sample)

I have a profile already setup in my directory - why can't I use it ?!

The directory ( top level after running the generate bundle)

![Capture](https://user-images.githubusercontent.com/47417716/56281640-0ea5fa00-6105-11e9-8638-fc34cc784da0.PNG)

**Comment by pcoop** [comment]
What sort of change do you have in mind? Would you like there to be --nodejsappXML and --nodejsappProfile parameters that could optionally be used to identify existing meta-data files to use when generating a NODEJSAPP? Or how about a --profileinclude parameter that would cause the generated profile to include another named profile from within the current bundle? If we take that route, should we perhaps have more parameters to set _NODEHOME_, _TZ_ and friends from the command line?

I'm asking as this use-case feels a little too off-piste to me, I'm wondering if you've thought of a usage pattern in which a naive user might legitimately encounter this requirement? Power users are of course able to modify the meta-data files however they like from first principles (including storing/recovering them to/from SCM), whereas _bundle generate_ is aimed at someone who isn't that familiar with CICS Bundles.

I don't think we're intending to support all of the customisation options that could be imagined within the _bundle generate_ command line, so what would make this scenario significant enough to be worth adding support for?

**Comment by ChrisAtkinson1** [comment]
This is a good question.

Maybe in my niaive user role I'd like it to autodetect the .profile.

The options on a command line are probably the second choice.  --profileinclude being my preference.

The other options may be nice to have - or indeed read in from some .properties file or something.

**Comment by matthewpwilson** [comment]
I think the straightforward answer here is that you can use your own profile, you'd just need to copy it over the top of the generated profile or modify the generate nodesjapp to point to your profile.
I'm inclined to agree with Paul here, I can't think of a use-case where Freyja would already have a profile in-hand, so I'm not sure it's worth going to too much effort here.

**Comment by ChrisPark89** [comment]
I also agree with Paul. If we compare this with Docker world, nodejs developers have to write their own Dockerfile, which is a somewhat similar to our profile, so I guess _bundle generate_ command is a helping tool, rather than a tool that has to provide everything.

**Comment by markcocker** [comment]
I think it unlikely a Node.js app will have an existing .profile. Rather, if the app had a need to set environment variables it would be an .env file and use a package such as https://www.npmjs.com/package/dotenv to read it - this should just work in when run in CICS.

More likely is the need to copy a .profile from another app that was deployed to CICS, in which case @matthewpwilson comments above apply - ie. they can copy the contents into the generate profile or copy over the generated file.

**Comment by ChrisAtkinson1** [comment]
As discussed above this is thought to be invalid.
