### ISSUE TITLE
Push should create directory specified by --targetdir option

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#78]
At the moment the z/OS directory specified by `--targetdir` option is required to exist and the bundle directory is created within it using mkdir. If `targetdir` directory not exist you get the error:
```
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to create directory '/u/cicprov/mnt/CICPY000/bundles/cics-nodejs-invoke_1.0.0'. Problem is: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 8
rc:       -1
reason:   93651005
message:  mkdir() error
```

It would be useful if any necessary parent directories were automatically created, for example using the `mkdir -p` option when creating the bundle directory. This enhancement would be useful when deploying a bundle to the file system created by z/OS Provisioning Toolkit. For example:
```shell
zowe cics-deploy push bundle --name INVOKE --targetdir /u/cicprov/mnt/CICPY000/bundles --overwrite
```
would work even though /bundles does not exist.

**Comment by pcoop** [comment]
I can switch back to using SSH to create the directory easily enough. But a side-effect of implementing this is that if the user enters a garbage directory then we'll do our best to create it for her anyway, potentially introducing new root level structures in the process... do we want that capability to be enabled by default?

Imagine she types:

  zowe cics-deploy push bundle --name test --targetdir /this/is/a/test

We'd go off and create that target structure for her (subject to permissions of course) polluting the root of the file system in the process. Perhaps there should be another switch that the user can set to request that the remote target directory be created? Or maybe we don't care, and if she asks for a wacky or typo'd directory we should do our best to create it for her regardless, without a similarly easy way to undo it afterwards.

I'm thinking a better option might be to detect that the target directory doesn't exist, and issue an error message suggesting a separate zowe command the user can enter to (attempt to) create it. It's her choice whether she runs that separate command or not... if she was the victim of a typo then she probably wont do so.

**Comment by markcocker** [comment]
> detect that the target directory doesn't exist, and issue an error message suggesting a separate zowe command the user can enter to (attempt to) create it.

ok that sounds good.

For the z/OS PT scenario, I realised there is an easy _workaround_ in that you can create an empty bundles directory in the image via 1) creating an empty bundles directory in the image source, then 2) add `copy bundles bundles` to zosptfile.

**Comment by markcocker** [comment]
Verified when `--targetdir` specifies a directory that does not exist I get an error and message suggesting a zowe command to create it. I then cut&pasted that command it successfully created the target directory.

```console
$ zowe cics-deploy push bundle --name INVOKE --targetdir /u/cicprov/mnt/CICPY000/does_not_exist --overwrite --verbose
Making remote bundle directory

Command Error:
A failure occurred during CICS bundle pushing.
 Reason = The target directory does not exist, consider creating it by issuing: 
zowe zos-uss issue ssh "mkdir -p /u/cicprov/mnt/CICPY000/does_not_exist"


cockerma@Marks-MacBook-Pro:~/git/cics-nodejs-invoke/projects/cics-nodejs-invoke$ zowe zos-uss issue ssh "mkdir -p /u/cicprov/mnt/CICPY000/does_not_exist"

$ mkdir -p /u/cicprov/mnt/CICPY000/does_not_exist
$ 
cockerma@Marks-MacBook-Pro:~/git/cics-nodejs-invoke/projects/cics-nodejs-invoke$ zowe zos-uss issue ssh 'ls -l /u/cicprov/mnt/CICPY000/'

$ ls -l /u/cicprov/mnt/CICPY000/
total 96
drwxrwxr-x   2 CICPROV  TSOUSER     8192 Apr 18 10:41 JVMProfiles
drwxrwxr-x   2 CICPROV  TSOUSER     8192 Apr 18 10:41 PROVISION_OK
drwxrwxr-x   3 CICPROV  TSOUSER     8192 Apr 18 14:24 bundles
drwxrwxr-x  13 CICPROV  TSOUSER     8192 Apr 18 10:41 dfhconfig
drwxr-xr-x   2 COCKERM  TSOUSER     8192 Apr 19 18:52 does_not_exist
drwxrwxr-x   3 CICPROV  TSOUSER     8192 Apr 18 14:27 workdir
$
```
