### ISSUE TITLE
Npm output not streamed back if --verbose is specified.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#79]
It is expected that npm output should be streamed back if verbose is specified - it is not.

Eg

Undeployed existing bundle from CICS
Removing the contents of the remote bundle directory
Uploading the bundle to the remote bundle directory
Running npm install for the remote bundle
Deploying the bundle to CICS
 ███_______| 33%  O | Waiting for JOB51833 to enter OUTPUT

**Comment by pcoop** [comment]
That does sound like the problem we've been having with SSH under Windows. Hopefully the SSH fix will resolve it.

**Comment by ChrisAtkinson1** [comment]
Works with the new update 💯
