### ISSUE TITLE
--verbose option results in repeated messages to the console

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#82]
Using the `--verbose` option on `zowe cics-deploy push bundle --name INVOKE --targetdir /u/cicprov/mnt/CICPY000/bundles --overwrite --verbose` results in the same messages repeated many times to the console. I copied the output into [log.txt](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3099110/log.txt) that is 544KB. I would expect CI-CD pipelines to commonly use the --verbose option to capture a full logs.

The log shows a second problem. I deliberately remove write permission from the bundle directory:
```console
$ ls -l /u/cicprov/mnt/CICPY000/bundles/
/u/cicprov/mnt/CICPY000/bundles/:
total 16
dr-xr-xr-x   6 COCKERM  TSOUSER     8192 Apr 18 15:58 cics-nodejs-invoke_1.0.0
```
and the command `zowe cics-deploy push bundle --name INVOKE --targetdir /u/cicprov/mnt/CICPY000/bundles --overwrite --verbose` duly shows an error when it attempts to remove the files within the bundle, but instead of failing, it continues :
```
Removing the contents of the remote bundle directory


$ cd /u/cicprov/mnt/CICPY000/bundles/cics-nodejs-invoke_1.0.0 && rm -r *
rm: FSUM9196 cannot remove directory "node_modules": EDC5111I Permission denied.
rm: FSUM9196 cannot remove directory "nodejsapps": EDC5111I Permission denied.
rm: FSUM9195 cannot unlink entry "package.json": EDC5111I Permission denied.
rm: FSUM9195 cannot unlink entry "package-lock.json": EDC5111I Permission denied.
rm: FSUM9196 cannot remove directory "public": EDC5111I Permission denied.
rm: FSUM9195 cannot unlink entry "server.js": EDC5111I Permission denied.
rm: FSUM9196 cannot remove directory "META-INF": EDC5111I Permission denied.
$ 
Uploading the bundle to the remote bundle directory
```

**Comment by pcoop** [comment]
The second problem is that at the moment there's no error code returned from the SSH client, we have to parse the console output to guess at whether it worked or failed... that heuristic logic is fairly primitive. When we delete the contents of a directory we tolerate the FSUM9195 message as that implies the directory was empty, but in this failure scenario there's a FSUM9195 that shouldn't be tolerated and shouldn't cause the other messages to be tolerated. I could add further special case code to cope with that, but it should be easier once the SSH client can report a failure code.

The first problem is something else entirely. I suspect that the screen is getting redrawn every time the progress bar updates, and that redraw is getting logged.

**Comment by pcoop** [comment]
The screen redrawing is an interplay between the scroll bar and the verbose logging... they don't seem to play well together. I can disable the scroll bar for --verbose mode, I'm just deciding how far to go with that. The scroll bar is useful during calls to DFHDPLOY as otherwise we get to wait ages with no output to screen, if I disable that scroll bar then --verbose might actually look less verbose than the normal output!

I've had a quick play, if I redirect the --verbose output to a console I currently get over 2Mb of console data. If I disable the scroll bar for PUSH (but leave it active for the submit-jobs sub-stage) I only get 86K of output. I still see some duplicate content, but tons less. Maybe that's an acceptable compromise? Seems to be an improvement anyway. I could disable the progress bar entirely, just not sure that'll be a good experience either.

**Comment by markcocker** [comment]
Using the #88 I now get:
`zowe cics-deploy push bundle --name INVOKE --targetdir /u/cicprov/mnt/CICPY000/bundles --overwrite --verbose` results in output: [output1.txt](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3108862/output1.txt)

`zowe cics-deploy push bundle --name INVOKE --targetdir /u/cicprov/mnt/CICPY000/bundles --overwrite --verbose > ~/Downloads/output.txt` results in the output redirection file: 
[output.txt](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3108863/output2.txt)

Both are difficult to follow as they contain repeated content. If `--verbose` is aimed at automation systems wanting to log as much activity as possible, then perhaps turning off the progress bar when this option is specified is the right behaviour.

I also noticed the last line of the output does not end with a CR, so the command prompt appears directly after it, rather than on the next line. This is true with and without the `--verbose` option.

**Comment by pcoop** [comment]
Okay, I'll remove the scroll bar entirely in verbose mode... that should generate the least verbose console output!

Incidentally, the part 2 problem for this issue should be fixed already, I'll take a look at the part 3 problem of a trailing CR too.

**Comment by markcocker** [comment]
> the last line of the output does not end with a CR

Verified this is fixed with and without `--verbose` option.

> I'll remove the scroll bar entirely in verbose mode

Verified scroll bar no longer shown with `--verbose` option, and is shown without the option.

> the part 2 problem for this issue should be fixed already

Verified the push command fails to remove existing files from the target bundle directory:
```
$ cd /u/cockerm/node/bundles/cics-nodejs-invoke_1.0.0 && rm -r *
rm: FSUM9196 cannot remove directory "nodejsapps": EDC5111I Permission denied.
rm: FSUM9196 cannot remove directory "public": EDC5111I Permission denied.
rm: FSUM9196 cannot remove directory "META-INF": EDC5111I Permission denied.
$ 
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to run 'rm -r *' in remote directory '/u/cockerm/node/bundles/cics-nodejs-invoke_1.0.0'. Problem is: The output from the remote command implied that an error occurred.
```
