### ISSUE TITLE
Deploying to multiple regions - and one region fails to enable.  Is this message good enough? 

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#83]
I am deploying to a scope with more than one region.  The second region fails to enable to the nodejsapp ( due to the port being in use on the first ).  The PUSH command reports this from the DFHDPLY output.  You have to delve deeper to see the reason.  Should we return anymore output to the user than what it currently does.  

Eg to find the reason you need to look in STDERR.

The error is shown in the node STDERR

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::30701

With MSGUSR giving.

DFHAP1900 04/23/2019 10:58:33 CALMAS3 NONE CICSUSER CONL SET BUNDLE(CICSMULT) ENABLESTATUS(ENABLED) RESP(NORMAL) RESP2(0).      
DFHSJ1304 E 04/23/2019 10:58:35 CALMAS3 CICSUSER NODEJSAPP CICSAPP1 has ended abnormally with return code 1.                    

Zowe push shows this error from DFHDPLY

C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\PUSH1\tests\CICSMULT>zowe cics-deploy push bundle --name CICSMULT --targetdir /u/atkinc/pushtest --zosmf-profile zosmf2c --cics-deploy-profile allregs --ssh-profile ssh2Ckey --ow
WARNING: No .zosAttributes file found in the bundle directory, default values will be applied.
WARNING: No .zosAttributes file found in the bundle directory, default values will be applied.
WARNING: No .zosAttributes file found in the bundle directory, default values will be applied.
WARNING: No .zosAttributes file found in the bundle directory, default values will be applied.
10:57:59.057965 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/23 10:57am
10:57:59.058603 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
10:57:59.059913 :  *
10:57:59.059920 :  SET CICSPLEX(CAPLEX);
10:58:01.078042 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
10:58:03.086085 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
10:58:03.101003 :
10:58:03.101013 :  *
10:58:03.101019 :  DEPLOY BUNDLE(CICSMULT)
10:58:03.101023 :         BUNDLEDIR(/u/atkinc/pushtest/CICSMULT_1.1.1)
10:58:03.101027 :         SCOPE(ALLREGIN)
10:58:03.101031 :         STATE(ENABLED)
10:58:09.149777 :  DFHRL2049I Creating BUNDLE definition.
10:58:09.156515 :  DFHRL2024I BUNDLE definition(CICSMULT) VERSION(1) successfully created.
10:58:10.160109 :  DFHRL2052I Installing BUNDLE definition.
10:58:10.160445 :  DFHRL2131I Waiting for BUNDLE(CICSMULT) to be installed in active regions in SCOPE(ALLREGIN).
10:58:29.277383 :  DFHRL2130I BUNDLE(CICSMULT) installed in 2 of 2 regions in SCOPE(ALLREGIN).
10:58:29.277432 :  DFHRL2054I Setting BUNDLE state to ENABLED.
10:58:40.346790 :  DFHRL2067W BUNDLE(CICSMULT) did not reach state ENABLED in all systems in SCOPE(ALLREGIN).
10:58:40.351913 :  DFHRL2129I BUNDLE(CICSMULT) state is INSTALLED on 2 CICS regions in SCOPE(ALLREGIN).
10:58:40.351954 :  DFHRL2129I BUNDLE(CICSMULT) state is DISABLED on 2 CICS regions in SCOPE(ALLREGIN).
10:58:40.351961 :
10:58:40.351964 :  Status of BUNDLE(CICSMULT) in SCOPE(ALLREGIN):
10:58:40.351968 :  CICS     STATUS       AVAILABILITY BUNDLE
10:58:40.351971 :  CALMAS1  DISABLED     NONE         CICSMULT
10:58:40.351975 :  CALMAS3  DISABLED     NONE         CICSMULT
10:58:40.353341 :
10:58:40.353346 :  All Bundle part records for BUNDLE(CICSMULT):
10:58:40.353350 :  CICS     BUNDLE   STATUS       AVAILABILITY BUNDLEPART
10:58:40.354049 :  CALMAS1  CICSMULT ENABLED      NONE         CICSAPP1 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.354849 :  CALMAS3  CICSMULT ENABLED      NONE         CICSAPP2 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.355767 :  CALMAS1  CICSMULT ENABLED      NONE         CICSAPP3 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.356510 :  CALMAS3  CICSMULT ENABLED      NONE         CICSAPP4 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.357295 :  CALMAS3  CICSMULT DISABLED     NONE         CICSAPP1 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.358242 :  CALMAS1  CICSMULT DISABLED     NONE         CICSAPP2 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.358972 :  CALMAS3  CICSMULT DISABLED     NONE         CICSAPP3 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.359758 :  CALMAS1  CICSMULT DISABLED     NONE         CICSAPP4 http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP
10:58:40.359763 :
10:58:40.359795 :  DFHRL2055I Errors have occurred, processing terminated.
10:58:40.367040 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

Command Error:
A failure occurred during CICS bundle pushing.
 Reason = DFHDPLOY stopped processing for JOBID JOB63569 due to an error.

**Comment by ChrisAtkinson1** [comment]
Bundle used.

[CICSMULT.zip](https://github.com/IBM/zowe-cli-cics-deploy-plugin/files/3106993/CICSMULT.zip)

**Comment by pcoop** [comment]
I'm not sure that we can do any more at the moment - all we know is what DFHDPLOY can tell us. If we take on the extra work to provide access to stderr/msgusr/etc. then it'll be a bit less difficult for the user to research these failures themselves. The good news is that the output does at least show the partial success/failure of the deploy action... the asynchronous windows are such that I wasn't sure we'd even have that much.

**Comment by tasha-m-k** [comment]
Docs: Add to KC Node Troubleshooting, maybe also the plugin troubleshooting.

**Comment by tasha-m-k** [comment]
Docs: Add to KC Node Troubleshooting, maybe also the plugin troubleshooting.

**Comment by tasha-m-k** [comment]
put a scenario in potential problems

now we have extra output, obvious place to start looking is in those files.
