### ISSUE TITLE
Return code could reflect which step failed.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#84]
Whilst PUSH reports on the stage eg npm fails etc - should it issue an error code for automation to use ?

**Comment by pcoop** [comment]
Sadly the return code can only be zero or one at the moment. The Zowe team are adding the ability for handlers to return a unique code, so I guess we could define a more interesting pattern of response codes at that time if we wanted to.

Is automation likely to care about the stage of failure though? I suspect that the underlying sub-commands will be more useful for scripting purposes, Push is primarily aimed at a user, someone who will read the output and barely care about the return code. We need a non-zero code for failure cases, but I don't see a strong need for more detail than that.

**Comment by ChrisAtkinson1** [comment]
Agree is aimed at user
