### ISSUE TITLE
Can we skip one of the commands?

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#85]
I don't see how or why you would. 

But it's a scenarion in the test plan for PUSH.

**Comment by pcoop** [comment]
It's possible to issue Undeploy and Deploy separately, and one can script the upload or the npm stuff separately too... it can all be done from first principles. But there's no way to do a partial push.

If we do integrate CMCI then there's the option of detecting whether an undeploy is actually needed and skipping that step where appropriate, but I don't think we're likely to do that any time soon.
