### ISSUE TITLE
The timer on PUSH goes up and down.  It does not increment nicely

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#87]
The timer on the PUSH command seems related to the step it is on.

So you see the time go to 34% 70% 18% etc.

It should step nicely upwards.

**Comment by pcoop** [comment]
Yup, there's not much I can do about it.

It's impossible to know how long some of the commands are going to take, so we can't give an accurate progression over time anyway, and as several of the Zowe supplied sub-commands reset the progress of the bar then it's out of our control anyway. The bar should be seen as confirmation that Zowe hasn't hung, not as a predictable and reliable way to determine how much longer the processing is going to take. I can remove the progress bar entirely if that would be preferable.

**Comment by matthewpwilson** [comment]
I'll raise an issue against Imperative about aggregation of things that use progress bars.  Also mention problems with resizing terminal windows with progress bars.

**Comment by matthewpwilson** [comment]
I have a change in works that will improve this.

**Comment by ChrisAtkinson1** [comment]
Seems good to me.
