### ISSUE TITLE
PUSH does not work in GIT BASH on Windows due to the directory issue.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#89]
This error on the --targetDir is the problem

$ zowe cics-deploy push bundle --name CICSJS03 --targetdir /u/atkinc/pushtest --zosmf-profile zosmf2c --cics-deploy-profile deploy --ssh-profile ssh2Ckey  --ow
Command Error:
A failure occurred during CICS bundle pushing.
 Reason = A problem occurred attempting to create directory '**U:/atkinc/pushtest/CICSJSON_1.0.0'**. Problem is: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 8
rc:       -1
reason:   93651005
message:  mkdir() error

**Comment by ChrisAtkinson1** [comment]
In test plan as 

Should work for git bash on Windows (... default shell often for Visual Studio code)

**Comment by pcoop** [comment]
Ah, so GitBash is corrupting the input parameters again... groan. Matthew put a change in to tolerate escaping of the directory name in a GitBash environment, is that sufficient?

**Comment by matthewpwilson** [comment]
The user needs to escape the slashes in GitBash; if this doesn't work then we need to normaise the path to make sure it does.

**Comment by ChrisAtkinson1** [comment]
Directory needs escaping //u//user//etc
