### ISSUE TITLE
If CICS does not have permission to the bundle directory DFHDPLOY gives unknown error

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#91]
Waiting for JOB69328 to enter OUTPUT (Processing DFHDPLOY DEPLOY action)

11:46:00.651039 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/24 11:46am
11:46:00.651788 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
11:46:00.653012 :  *
11:46:00.653019 :  SET CICSPLEX(CAPLEX);
11:46:02.670416 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
11:46:04.683749 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
11:46:04.700320 :
11:46:04.700339 :  *
11:46:04.700346 :  DEPLOY BUNDLE(CICSJS02)
11:46:04.700351 :         BUNDLEDIR(/u/atkinc2/CICSJSON_1.0.0)
11:46:04.700355 :         SCOPE(CALMAS1)
11:46:04.700359 :         STATE(ENABLED)
11:46:04.700363 :         CSDGROUP(PUSHTEST);
11:46:04.706854 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
11:46:12.771460 :  DFHRL2051I Creating BUNDLE definition on the CSD in system(CALMAS1 ).
11:46:12.891344 :  DFHRL2049I Creating BUNDLE definition.
This is the error that DFHDPLY gives - should the error (MSGUSR) be sent to the user ?

11:46:12.897641 :  DFHRL2024I BUNDLE definition(CICSJS02) VERSION(3) successfully created.
11:46:13.901118 :  DFHRL2052I Installing BUNDLE definition.
11:46:13.901520 :  DFHRL2131I Waiting for BUNDLE(CICSJS02) to be installed in active regions in SCOPE(CALMAS1).
11:46:15.916293 :  DFHRL2300E BUNDLE(CICSJS02) cannot be deployed. The reason for the failure could not be determined.
11:46:15.922147 :  DFHRL2055I Errors have occurred, processing terminated.
11:46:15.927066 :  DFHRL2014I Disconnecting from CICSPLEX(CAPLEX).

The actual error is found in MSGUSR

DFHRL0106 E 04/24/2019 11:46:13 CALMAS1 COIE The CICS resource lifecycle manager failed to create the BUNDLE resource CICSJS02     
           because CICS is not authorized to read the manifest /u/atkinc2/CICSJSON_1.0.0/META-INF/cics.xml in the root directory of
           the bundle.                                                                                                             
DFHRL0110 E 04/24/2019 11:46:13 CALMAS1 COIE The CICS resource lifecycle manager has failed to create the BUNDLE resource CICSJS02.

**Comment by pcoop** [comment]
There have been questions about this before.

Capturing MSGUSR is a bigger job, we're thinking about that as part of a different work item. What's more relevant for now is whether we'd like to provide a simple mechanism to chmod the uploaded bundle structure; we could make that part of the PUSH command, if the user knows how they want it to be set to. The entire directory structure would need to be set correctly of course. It's not clear to me what the best behaviour should be, but offering a --targetDirAttrs parameter (or similar) does feel within the scope of what we could offer.

**Comment by tasha-m-k** [comment]
Docs: Make it clear where the attributes are coming from in: 
1. troubleshooting
