### ISSUE TITLE
Behaviour of 'npm install' with unconfigured USS environment

### ISSUE THREAD

**Issue by pcoop** [IBM/zowe-cli-cics-deploy-plugin#92]
In order to run npm in a remote shell we need the remote PATH statement to be configured, we probably also need some environment variables set so that the native compiler will run. If our user has configured their .profile then that configuration may have already been done... but what if they haven't?

At the moment the PUSH command tweaks their %PATH% statement to add the default installation directory of node.js to the end of their path. That's perhaps a step in the right direction, but it's probably not sufficient, and what if node.js wasn't installed at the default location? Will the default change with Node 8 and beyond?

Things we could do to improve the experience:

 1) We could figure out what environment variables are needed for the compiler, then set them automatically too.
 2) We could update the docs to emphasise that this remote configuration is a requirement. We could even offer zowe commands to do it.

We could go further, perhaps adding the remote installation location of node.js to the cics-deploy profile. But, if we do that, why bother having the %INCLUDE file in the NODEJSAPP's profile... we might as well hard code it. Maybe that's a better thing to do anyway, but it's a significant change to the work-flow that we'd envisaged.

 3) We could add NODEHOME to the cics-deploy profile and use that to configure the remote PATH automatically.
 4) We could use that value in order to remove the need for %INCLUDE in the profile.

Alternatively, we could attempt to read the remote file that %INCLUDE points to, see what has been configured for NODEHOME there, and use that. If we do that then we can issue better error messages if the remote file doesn't exist. It may in turn have further %INCLUDE statements within it, so maybe we should walk that entire tree of files looking for what NODEHOME will resolve to. But how far down the path of duplicating the CICS validation logic should we go?

 5) We could lookup the remote %INCLUDE file to find the remote value of NODEHOME.
 6) We could proactively detect and report errors that would normally be found during the resource installation process.

We could get away with doing very little beyond what we already have, or put some effort into doing a good chunk more.

**Comment by matthewpwilson** [comment]
Intend to add the minimum set of env vars automatically in order for npm to build native addons e.g. node-expat. Need to be careful about overriding things the user might have set deliberately e.g. _CEE_RUNOPTS, might need to a parameter to avoid this.

**Comment by markcocker** [comment]
Suggest doc is updated to say users' .profile on z/OS needs to be configured if default version of npm and associated environment variables for compiling natives need to be customised.

As a FYI, the location npm being used can be seen in the output when the `--verbose` option is used:
```
$ cd /u/cicprov/mnt/CICPY000/bundles/cics-nodejs-invoke_1.0.0 && export PATH="$
PATH:/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin" && npm install
```

**Comment by pcoop** [comment]
I've had a go at trying to add a few extra environment variables so that remote native compilation will work... turns out it's not that simple. I tried adding node-xpat which has a native build; that in turn needs a whole load of Rocket tools to be installed, none of which have a predictable installation location. That in turn means that we can't easily guess at what the PATH, LIBPATH, etc. will need updating with.

Adding the default node installation location automatically remains useful as a lot of npm commands will 'just work' with that; but it looks like we're going to have to rely on doc to cover the broader issue of configuring the user's .profile with the full stack of Rocket tools (Perl, Python, etc.).

**Comment by markcocker** [comment]
I have added guidance in topic **Create Zowe CLI profiles** in PR #148.

We could also add text to the topic Troubleshooting with symptoms if the user .profile is not setup correctly and link back to the above guidance.

**Comment by tasha-m-k** [comment]
@cxharris just checking you've seen Mark's comment above re Troubleshooting as you're working on that topic?

**Comment by tasha-m-k** [comment]
In requirements: optional step - if you're running Node applications, install Node.js (mention Rocket).

In deploying your first app: add step before 5 to check node and npm versions.

**Comment by cxharris** [comment]
PR #289
