### ISSUE TITLE
Should we do anything to prevent a user removing another persons bundle ?

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#93]
Should we do anything to prevent a user removing another persons bundle ?

My thoughts is it is how the CICS is setup.

I can UNDEPLOY a bundle if I am allowed access to the resource.

I can overwrite files if I am allowed by file permissions.

So I think this is normal working practice.  So assume we should NOT be doing anything special to guard against this.

**Comment by ChrisAtkinson1** [comment]
Opened for discussion as someone added a test for this.

**Comment by pcoop** [comment]
Authorisation is the first line of defence. If our user is deliberately trying to replace/update something originally deployed by someone else, so be it, that's a valid thing to do. I'm more interested in defending our user against accidentally replacing something that they hadn't intended to replace, we should do what we can to avoid accidents.

We currently require --overwrite be set before we'll replace something that already exists. We could go a bit further; for example, we could check to see if the version number of the local bundle is greater than or equal to the version number of what's already present in the remote file system; if it's lower we might refuse to replace what appears to be a newer version (or at least require another override be set before doing so). We could use CMCI to query the installed BUNDLE in the remote CICS to see if it has the same id/version as that of the local bundle; that might protect against accidental clashes on the same resource name. Whether it's worth the effort of implementing this extra validation is open to discussion, but we have the option of doing more than just offering --overwrite.
