### ISSUE TITLE
The minimum timeout option is too low.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#94]
For this test.

What if an already deployed app is doing something asynchronously
Does this mean takes longer than --timeout to complete undeploy? - this depends on the timeout.  The default of 0 waits long enough.  

However normal bundles I see the minimum being too low.  Around 25 secs is the quickest I have seen so far for a bundle to UNDEPLOY/DEPLOY successfully.

The --timeout range is from 1 to 1800 seconds.  It appears to me the low value is overly optomistic for the job to complete.  

Eg This is the error with a timeout of 23 secs.

Waiting for JOB70446 to enter OUTPUT (Processing DFHDPLOY UNDEPLOY action)

14:43:19.223325 :  DFHDPLOY CICS TS APPLICATION DEPLOYMENT  2019/04/24 2:43pm
14:43:19.224057 :  RELEASE: HCI7300.   SERVICE LEVEL: HCI7300.
14:43:19.225335 :  *
14:43:19.225342 :  SET CICSPLEX(CAPLEX);
14:43:21.246095 :  DFHRL2119I Connection to CMAS(CACMASA ) successful.
14:43:23.262380 :  DFHRL2013I Connection to CICSPLEX(CAPLEX) successful.
14:43:23.279826 :
14:43:23.279838 :  *
14:43:23.279844 :  UNDEPLOY BUNDLE(CICSJS02)
14:43:23.279849 :         SCOPE(CALMAS1)
14:43:23.279853 :         STATE(DISCARDED)
14:43:23.279857 :         TIMEOUT(23)
14:43:23.279861 :         CSDGROUP(PUSHTEST);
14:43:23.280478 :  DFHRL2132I Analyzing CICS regions and CSD attributes.
14:43:30.341256 :  DFHRL2093I BUNDLE(CICSJS02) found in SCOPE(CALMAS1).
14:43:30.341332 :  DFHRL2129I BUNDLE(CICSJS02) state is INSTALLED on 1 CICS regions in SCOPE(CALMAS1).
14:43:30.341367 :  DFHRL2129I BUNDLE(CICSJS02) state is ENABLED on 1 CICS regions in SCOPE(CALMAS1).
14:43:30.341397 :  DFHRL2054I Setting BUNDLE state to DISABLED.
14:43:41.429903 :  DFHRL2042I Discarding BUNDLE(CICSJS02).
14:43:49.543986 :  DFHRL2039W The command failed to complete within the specified time out period of 23 seconds.
14:43:49.544110 :  DFHRL2041I TIMEOUT has occurred before BUNDLE(CICSJS02) has reached STATE(DISCARDED)
14:43:49.546452 :  DFHRL2055I Errors have occurred, processing terminal

**Comment by pcoop** [comment]
The 1:1800 timeout is something we've inherited from DFHDPLOY, it offers that range. We can restrict it if we want to, but we can't offer more without changing DFHDPLOY itself. DFHDPLOY implements a default timeout of 300 seconds.

What's most important for us is that, whatever the timeout is set to, if it triggers we report the issue correctly. DFHDPLOY has done that, so it feels broadly okay to me. 1 second is clearly too small a timeout, but that's true whether you call DFHDPLOY directly or whether you use PUSH; we could report an issue against DFHDPLOY to shrink their timeout window to something more sensible but I don't see much point, we're just exposing their configuration option.

The default of 300 seconds ought to be sufficient even if there's a Bundle with a NODEJSAPP that wants to take 30 seconds to terminate, so I don't think we need to do anything.

**Comment by tasha-m-k** [comment]
Document: if not set, the default of DFHDPLOY is used.

**Comment by markcocker** [comment]
@ChrisAtkinson1 I have updated the help for timeout on commands `zowe cics-deploy deploy bundle`, `zowe cics-deploy undeploy bundle` and `zowe cics-deploy push bundle` to read:

> An optional numerical value that specifies the maximum amount of time in seconds (1 - 1800 inclusive) for the DFHDPLOY command to complete. If not specified DFHDPLOY will use its default of 300 seconds.

Is this good enough to close this issue?

**Comment by ChrisAtkinson1** [comment]
Yes I think that is enough.
