### ISSUE TITLE
Time for push normally longer than a minute in total.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#95]
With undeploy as well required the time taken is around 70 secs on average.  How acceptable this is and the effects on network/system load I am not sure.

We had this target in the test plan.

How long does the push take? We are aiming for about 30seconds. Will be good for the doc to set expectations (eg. "less than a 1 minute, depending on system load") - That is going to depend on system load too!

**Comment by pcoop** [comment]
Here's the timing for one of my jobs (timestamps are from the log file)

11:32:34 start
11:32:35->11:33:02 waiting for UNDEPLOY job
11:33:02->11:33:05 Emptying remote directory using SSH
11:33:05->11:33:07 Uploading Bundle
11:33:07->11:33:19 Running npm install using SSH
11:33:19->11:33:50 waiting for DEPLOY job
11:33:50 end

Roughly:
26 seconds of DFHDPLOY UNDPLOY
3 seconds of cleaning the file system
2 seconds of upload
12 seconds of npm
31 seconds of DFHDPLOY DPLOY

For a total of 76 seconds.

**Comment by tasha-m-k** [comment]
Document expectation of timing
Add troubleshooting section to say: raise an issue on Github and point to this file

**Comment by pcoop** [comment]
It's perhaps worth noting that the user testing we conducted yesterday didn't flag the elapsed time as a concern. It's only a sample of 1, but the impression was that 90ish seconds is not unreasonable.

**Comment by markcocker** [comment]
I have added the following text to [Deploying your first app](https://ibm.github.io/zowe-cli-cics-deploy-plugin/cdp-Deploying-your-first-app.html) to set the users expectation:

> A progress bar is shown and updated as the CICS bundle is deployed and the application is started. This can take a few minutes.

**Comment by ChrisAtkinson1** [comment]
Think this can close with the documentation being done.
