### ISSUE TITLE
Should push allow --attributes ?

### ISSUE THREAD

**Issue by ChrisAtkinson1** [IBM/zowe-cli-cics-deploy-plugin#96]
In the test plan this is asked.

Can the --attributes parameter be used?  

Currently no as it is not on the command line.

Unknown argument: attributes
Command failed due to improper syntax

**Comment by pcoop** [comment]
If I type 'zowe --attributes' I get a list of all the commands that zowe supports, including cics-deploy. Is that what this issue is about? If so, we've not done anything to break it, it's a standard part of Zowe.

**Comment by matthewpwilson** [comment]
zowe files dir-to-uss allows you to specify --attributes to specify something other than ./.zosattributes. However, push works only on the working directory, so we don't think we need this.
