### ISSUE TITLE
Progress bars give many lines of output in Gnome Terminal

### ISSUE THREAD

**Issue by matthewpwilson** [IBM/zowe-cli-cics-deploy-plugin#97]
I've just noticed that when using Gnome Terminal (the default terminal on RHEL), progress bars give me a new line of output for each 'tick' rather than redrawing the screen:  When using the embedded terminal in VSCode, progress bars work as expected.

I'm seeing this for both `deploiy` and `push`
It occurs while watching 'live' as well as when scrolling back through the output.
![image](https://user-images.githubusercontent.com/23260673/56736974-59f18580-6761-11e9-8bf0-cf13a443bbb4.png)

I think this is unlikely to be our problem however!

**Comment by markcocker** [comment]
For me on a Mac I have found this depends on the window width - if the widow is narrower than text on the progress bar message line you'll see this issue, however if the window is wider it works.

**Comment by matthewpwilson** [comment]
Ah yes I see the same behaviour.

**Comment by markcocker** [comment]
@matthewpwilson Shall I raise an issue against the Zowe CLI, or does this progress bar come from another project?

**Comment by matthewpwilson** [comment]
The progress bar stuff is part of imperative https://github.com/zowe/imperative/

**Comment by markcocker** [comment]
It looks like this could be a dupe of https://github.com/visionmedia/node-progress/issues/184

**Comment by pcoop** [comment]
I can truncate the status message that gets added to the bar if we know what a reasonable maximum width is.
