### ISSUE TITLE
Add option to push and deploy commands to specify the BUNDLE resource description

### ISSUE THREAD

**Issue by markcocker** [IBM/zowe-cli-cics-deploy-plugin#99]
The BUNDLE resource created as a result of `cics-deploy push bundle` and `cics-deploy deploy bundle` always has the description `CREATED BY DFHDPLOY`. This is the default if DESCRIPTION() is not specified on the DEPLOY BUNDLE script command. It would be nice if this description could be provided in an option on these commands and passed through to DFHDPLOY.

**Comment by pcoop** [comment]
That seems reasonable. At some point in the past we had a design document that listed the specific DFHDPLOY parameters we wanted to expose, but since then we've exposed all of them except this parameter... so we might as well do this too for completeness.

**Comment by markcocker** [comment]
Verified:
- `--description` or `--desc` can be used with `push bundle` and `deploy bundle`
- Error produced when 0 or >58 characters specified
- Use of quotes to specify a description that contains spaces
- BUNDLE resource defined with the value from `--description`
-  `--description` appears in generated CLIReadme.md

@ChrisAtkinson1 FYI
